### ISSUE TITLE
doesn't recognise liquid file w/ liquid language atom plugin included

### ISSUE THREAD

**Issue by sturobson** [emmetio/emmet-atom#102]
Moving this over to here from here - https://github.com/atom/language-html/pull/30 - as expected behaviour when having the language liquid plugin (https://atom.io/packages/language-liquid) applied would be that emmet should work. It's not the case unless adding 'liquid' to the language HTML plugin as mentioned - https://atom.io/packages/language-liquid - but it's suggested there's something in the emmet-atom plugin that should be doing this.

**Comment by silvenon** [comment]
Also, where do I add this `snippets.json` file? Can I make it work with [language-nunjucks](https://github.com/alohaas/language-nunjucks) too?

**Comment by sergeche** [comment]
Just pushed v2.3.2 where you can easily add Tab expander for custom syntaxes:  https://github.com/emmetio/emmet-atom#tab-key

**Comment by silvenon** [comment]
Works great, thanks!

**Comment by segersalex** [comment]
Open your keymap file.
(On mac) From the menubar, navigate to `Atom > Keymap..`  to open it.
At the bottom of the file, `keymap.cson`, add the following :
```
'atom-text-editor[data-grammar="text html liquid"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```
This basically tells atom to trigger emmet whenever you press tab within a file ending in`.liquid`.
Hope this worked for you!

**Comment by cungnguyentran** [comment]
@segersalex Thank you. You're the man!

**Comment by ey-charles** [comment]
> Open your keymap file.
> (On mac) From the menubar, navigate to `Atom > Keymap..` to open it.
> At the bottom of the file, `keymap.cson`, add the following :
> 
> ```
> 'atom-text-editor[data-grammar="text html liquid"]:not([mini])':
>     'tab': 'emmet:expand-abbreviation-with-tab'
> ```
> 
> This basically tells atom to trigger emmet whenever you press tab within a file ending in`.liquid`.
> Hope this worked for you!

This worked like a charm
