### ISSUE TITLE
Installing “emmet@2.1.1” failed.

### ISSUE THREAD

**Issue by Sigmanor** [emmetio/emmet-atom#105]
npm http GET https://registry.npmjs.org/emmet
npm http 304 https://registry.npmjs.org/emmet
npm http GET https://registry.npmjs.org/requirejs
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Alex\\.atom\\.apmrc" "install" "C:\\Users\\Alex\\.atom\\.node-gyp\\.atom\\.apm\\emmet\\2.1.1\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Alex\AppData\Local\Temp\apm-install-dir-114525-1028-15csrs1
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/requirejs
npm

System - Windows 8.1
Using http://atom.someguy123.com/ atom build for windows

**Comment by silvenon** [comment]
Yep, the latest released worked for me.
