### ISSUE TITLE
Unable to expand abbreviation "!" (basic HTML page) when working on .erb files

### ISSUE THREAD

**Issue by afifsohaili** [emmetio/emmet-atom#112]
Trying to expand "!" results in "<!></!>" instead of the basic HTML structure. Only happens when working on .erb files. Expanding "!" into the basic HTML structure works fine when working on .html files.

Mac OS X Mavericks
Atom 0.115.0
##

**Comment by silvenon** [comment]
Probably duplicate of #104.
