### ISSUE TITLE
Not working for erb (rails) file

### ISSUE THREAD

**Issue by tjwudi** [emmetio/emmet-atom#151]
It seems like that emmet-atom is not working on the filetype **HTML (Ruby - ERB)**. When I try to expand `input.e`, it does not expand. Then I changed the filetype to **HTML**, and everything looks good.

**Comment by sergeche** [comment]
Just pushed v2.3.2 where you can easily add Tab expander for custom syntaxes:  https://github.com/emmetio/emmet-atom#tab-key
