### ISSUE TITLE
Emmet: no such extension folder

### ISSUE THREAD

**Issue by Sensiblemnd** [emmetio/emmet-atom#152]
Loading Emmet extensions from ~/emmet /c:/Users/dev/.atom/packages/emmet/lib/emmet.coffee:115
Emmet: no such extension folder: C:\Users\dev/emmet

**Comment by rubielhum** [comment]
events.js:160 Uncaught Error: spawn php ENOENT
Emmet: no such extension folder: C:\Users\my/emmet 
I do not know how to solve it, thank you

**Comment by hex0gen** [comment]
This strange, but reinstallation of plugin is was a solution in my case. Herewith nothing is changed in the configuration of the plugin and this is a strange thing.

**Comment by JonDRamer** [comment]
Why is this closed with no valid solution?

**Comment by jasonleonhard** [comment]
mkdir /Users/$USER/emmet and the error will go away from the devtools console in Atom. It will still say Loading Emmet extensions from ~/emmet which I find annoying, still, it is an improvement.

**Comment by JonDRamer** [comment]
Thanks for the tip @jasonleonhard.  Hopefully we will get a solution at some point.

**Comment by itwebmaster** [comment]
=)) Hello guys! You can read the last paragraph [readme.md of this plugin](https://github.com/emmetio/emmet-atom#extensions-support):

> ### Support extension
> You can easily extend Emmet with new actions and filters or customize existing ones. In the "Settings"> "Emmet" section, set the extension path to the folder with the Emmet extensions. The default is ~/emmet. emmet in the home directory of your system.
> 

Hence the conclusion
This plugin tries to find this folder "~ /emmet"  _("<WinDrive(C)>:\Users\<CurrentUser>\emmet" - on Windows)_

## And the solution to this problem.

- You just need to create this folder (**empty**) _("<WinDrive(C)>:\Users\<CurrentUser>\emmet" - on Windows)_
_OR_
- [If you want to extend emmet](https://docs.emmet.io/customization/)
