### ISSUE TITLE
What's the equivalent of Rename Tag of sublime text in atom?

### ISSUE THREAD

**Issue by stevemao** [emmetio/emmet-atom#154]
What's the equivalent of Rename Tag of sublime text in atom?

**Comment by silvenon** [comment]
This is the correct answer and can be closed.

**Comment by stevemao** [comment]
Thanks

**Comment by peterblazejewicz** [comment]
You're welcome :+1:

**Comment by ahmadawais** [comment]
I think it is `(Super) + Shift + K // Rename tag shortcut` now.

**Comment by Zlatov** [comment]
Did this keyboard shortcut stop working for me alone? (Build 3211)

Also, the key combination stopped working: "Ctrl + Shift + :" (deleting the current tag, not content)

And "ctrl + shift + g" (wrap the selection with a tag).
