### ISSUE TITLE
Return key not working in Atom

### ISSUE THREAD

**Issue by alexbenson07** [emmetio/emmet-atom#155]
When I opened Atom today, my return key wasn't working on any of my files. I had a lot of errors in console from emmet, and so I disabled it and it worked.

**Comment by daithi-coombes** [comment]
getting issue with `enter` and `tab`. Only appeared after I updated, in this order, packages then atom. I was also updating from an old version of atom (about 5 months but no idea of what previous version is) to `0.168.0`. Emmet is updated to `2.3.0`.

`shift + enter` works for enter but have nothing to fix tab so Emmet is disabled for now.

**Comment by liamdawson** [comment]
@daithi-coombes I'm experiencing the same issue.

**Comment by marcker** [comment]
+ 1 :cry:

**Comment by sergeche** [comment]
Please check DevTools console for errors

**Comment by CMRahman** [comment]
I started experiencing the same issue today. But it is pretty consistent. Exiting & Restarting doesn't help. Also the dev console doesn't show any error.

**Comment by pgnfrsh** [comment]
Turning Emmet off and back on again fixed it (for now).

**Comment by daithi-coombes** [comment]
tried turning on/off and no joy.

in `dev tools` seems to be looking for a folder that doesn't exist:
```
Loading Emmet extensions from ~/emmet
    /home/daithi/.atom/packages/emmet/lib/emmet.coffee:115
Emmet: no such extension folder: /home/daithi/emmet
    /home/daithi/.atom/packages/emmet/lib/emmet.coffee:132 
```

**Comment by curtisblackwell** [comment]
I believe my problem was that I had the Snippets package disabled.

**Comment by CMRahman** [comment]
Disabling the "Emmet" plug-in seems to solve this issue for me.

**Comment by Marco85180** [comment]
Updating package will fix it :)

**Comment by CMRahman** [comment]
Sure did. Thanks. :)

**Comment by Mujaddadi** [comment]
Same problem. Disabling Emmett fixed it.
