### ISSUE TITLE
Balance (outward) hotkey Replaces Core Atom hotkey

### ISSUE THREAD

**Issue by burabure** [emmetio/emmet-atom#166]
Balance (outward) in windows/linux (ctrl + ,) is replacing the core atom hotkey for open settings view

**Comment by CalebKester** [comment]
Anyone have a fix for this? Trying to find the config for it.

**Comment by rkmax** [comment]
I have to uninstall for the same problem

**Comment by rkmax** [comment]
I did this change to fixed

**Comment by geovanisouza92** [comment]
+1
