### ISSUE TITLE
PHP -- Use HTML snippet expansions

### ISSUE THREAD

**Issue by zslabs** [emmetio/emmet-atom#181]
Hi,
Often times (WordPress dev) there's both PHP and HTML mixed into the same page. Right now, HTML expansions don't seem to work when your syntax is set to PHP -- is there a setting I could be overlooking with this? I use Emmet in Sublime and it works fine. Thanks!

**Comment by sergeche** [comment]
Just pushed v2.3.2 where you can easily add Tab expander for custom syntaxes:  https://github.com/emmetio/emmet-atom#tab-key
