### ISSUE TITLE
Disable tab expanding unknown tags.

### ISSUE THREAD

**Issue by ex-jedi** [emmetio/emmet-atom#182]
Is there a way to stop Emmet expanding unknown tags on tab, but without having to disable tab expansion entirely? It's over riding my snippets, which makes it the one thing keeping me from jumping off Sublime, which seems to handle this a bit better at the mo.

**Comment by silvenon** [comment]
Looks like a duplicate of #146.

**Comment by ex-jedi** [comment]
Belatedly... So it is.
