### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by neoxile** [emmetio/emmet-atom#184]
Emmet does not appear to be working for me on ATOM .168 i just installed the latest version but when i try to type code I get nothing.

I have tried installing it through ATOM and via github but neither are working

**Comment by ck86** [comment]
I've just updated ATOM and have the same issue.

**Comment by jesperronn** [comment]
sounds like duplicate of #183 ?

**Comment by ck86** [comment]
I don't think it's a broken keybinding, emmet itself does not work.

**Comment by sergeche** [comment]
Please check DevTools console for errors

**Comment by jonathandelgado** [comment]
+1, @jesperronn yeah, I think the keybinding issue I described is a byproduct of this.

**Comment by ck86** [comment]
@sergeche Same here. 

There is an awkward workaround to get it work if you disable and enable it on the settings page.

**Comment by sergeche** [comment]
I don’t see any errors either. Maybe a bug with extension update? Try to reinstall Emmet package

**Comment by kptech** [comment]
![default](https://cloud.githubusercontent.com/assets/1910154/5678155/be86db10-9832-11e4-8296-22ec5e7e8289.png)
---
I'm tried setting "Extention Path" (Default -> ~/.atom/packages/emmet), then I got the following error.
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
Unable to eval "c:\Users\<USERNAME>\.atom\packages\emmet\generate-menu.js" file: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
It seems like, cause of a problem "Content Security Policy".
Do you see the same error also in other environments?

**Comment by sergeche** [comment]
@kptech Emmet’s “Extensions path” is for Emmet extensions, not Atom’s: http://docs.emmet.io/customization/

**Comment by OverZealous** [comment]
:+1:

This was highly annoying: I updated and suddenly couldn't type <kbd>enter</kbd> from within a JSON file.  Emmet shouldn't even be active for a JSON file.

**Comment by danielmahon** [comment]
same problem here, return key doesnt work, shift-return does

**Comment by sergeche** [comment]
Guys, please check DevTools console for errors and try workarounds described here.

**Comment by danielmahon** [comment]
@sergeche no errors, disable and re-enabling workaround works, will try to rule out interference with other packages

**Comment by sergeche** [comment]
Might be a temporary issue with wrong extension unloading or something. Does it work fine if you restart editor?

**Comment by jonathandelgado** [comment]
@sergeche I've tried reinstalling the package, toggling enabled and restarting the editor. There is defiantly something wrong with the package.

**Comment by sergeche** [comment]
@jonathandelgado it still doesn’t work for you? What’s your OS?

**Comment by sergeche** [comment]
Can you open Packages > Keybinding Resolver and give a screenshot of output when you hit Enter key?

**Comment by danielmahon** [comment]
![atom-package_js_-__users_daniel__trash_my-package_2_03_15_pm_-_atom](https://cloud.githubusercontent.com/assets/1088089/5686613/7ff23b9e-9812-11e4-8c6d-e01556c07898.jpg)

**Comment by danielmahon** [comment]
**before disable/enable** (broken)

![atom-package_js_-__users_daniel__trash_my-package_2_03_15_pm_-_atom](https://cloud.githubusercontent.com/assets/1088089/5686613/7ff23b9e-9812-11e4-8c6d-e01556c07898.jpg)

**after disable/enable** (working)

![atom-package_js_-__users_daniel__trash_my-package_2_03_15_pm_-_atom](https://cloud.githubusercontent.com/assets/1088089/5686650/d421b80c-9812-11e4-8c71-09137f0b951f.jpg)

**Comment by sergeche** [comment]
Go to Emmet preferences and uncheck `Format line breaks` for broken scenario: does it work for you?

**Comment by danielmahon** [comment]
no change and same key binding result

**Comment by sergeche** [comment]
What’s the document syntax?

**Comment by danielmahon** [comment]
confirmed with .js, .html and .json (looks like it affects everything)

**Comment by danielmahon** [comment]
v0.169.0 btw

**Comment by sergeche** [comment]
Can we connect via TeamViewer so I can debug this issue?

**Comment by danielmahon** [comment]
sure

**Comment by sergeche** [comment]
Can you send me your ID and password at serge.che@gmail.com?

**Comment by ck86** [comment]
@sergeche I've found a possible bug.

The emmet actions will be added to the active editor views on activation, but not on views after that.
I've made some changes which you can see [here](https://gist.github.com/ck86/6f5d587e3d05405785ff#file-emmet-coffee-L127-L138), if it is fine I can make a pull request or you just copy&paste.

**Comment by danielmahon** [comment]
@sergeche actually not going to be able to at the moment, will let you know if get a sec

**Comment by sergeche** [comment]
@ck86 thanks. That’s looks like a workaround but I’d like to figure out what actually happens there. On my setup everything works fine, so I’m afraid this fix might still cause problems for some users

**Comment by danielmahon** [comment]
@sergeche sending you creds, I have a few minutes if you can make get on quickly

**Comment by sergeche** [comment]
The problem is that, for some reason, Atom didn’t registered Emmet actions for editor view during editor start-up. Thus, when you hit Enter, Atom tries to perform action that doesn’t exists. It’s pretty weird that this happens randomly.

The fix from @ck86 might help here. I have to dig into Atom API to find out what happens there

**Comment by liamdawson** [comment]
@sergeche any chance we can have a fix published, even if it's temporary?

**Comment by sergeche** [comment]
I’m not sure if this patch actually fixes problem. The problem is somewhere inside Atom guts. You can try this fix for yourself and see if it helps

**Comment by sergeche** [comment]
Please check v2.3.1

**Comment by jonathandelgado** [comment]
@sergeche 2.3.1 seems to work for me, thanks!

On a side note, https://github.com/AtomLinter/Linter/issues/319 had some interesting problems with apm caching packages, that might have been what was occurring here as well?

**Comment by astericky** [comment]
Emmet is unusable in atom for me.

**Comment by sergeche** [comment]
@astericky your comment is very insightful and helps me a lot to solve problems.

PS: please describe what “unusable” means to you: Emmet it doesn’t work at all or works not as you expect?

**Comment by astericky** [comment]
I type in div.search hit tab and get display: .search;

**Comment by sergeche** [comment]
It looks like your document syntax is set to something like CSS. Try to switch to HTML

**Comment by astericky** [comment]
I set it to HTML and it still behaves like CSS.

**Comment by astericky** [comment]
Ohh I see it just worked now. I restarted my atom and disabled and reinstalled emmet.

**Comment by jonathandelgado** [comment]
@sergeche This can probably be closed now, this was resolved a while ago!

**Comment by astericky** [comment]
FYI, if you have an error in your style tag css emmet will think you are working in CSS and won't render the html as you would expect. I just realized that that may have been the real error and not anything with emmet specifically.
