### ISSUE TITLE
ctrl-e conflict with atom keybindings update

### ISSUE THREAD

**Issue by KeitIG** [emmetio/emmet-atom#187]
Hi,

I don't really know if I should report this here or on Atom's repo, anyway.

ctrl-e now triggers `find-and-replace:use-selection-as-find-pattern` and override `emmet:expand-abbreviation`

**Comment by sergeche** [comment]
Are you on Mac or PC?

**Comment by KeitIG** [comment]
On Linux, here is a screenshot.

![capture du 2015-01-14 13 48 05](https://cloud.githubusercontent.com/assets/1311607/5739016/02e2002c-9bf4-11e4-8fad-e58c12b83580.png)

The new Atom keybinding seems to be only enabled for win32 and linux.

**Comment by sergeche** [comment]
Selector for `find-and-replace:use-selection-as-find-pattern` action has higher specificity. You have to re-define keyboard shortcut manually: https://atom.io/docs/v0.172.0/advanced/keymaps

**Comment by KeitIG** [comment]
I guess I should indeed. 

It is really boring that Atom has so much conflicts out-of-the-box, even if you can't really do anything against it. I will post something about that on discuss.atom.io.
