### ISSUE TITLE
Add Attributes to Wrap in Tag

### ISSUE THREAD

**Issue by dannymichel** [emmetio/emmet-atom#191]
My only complaint is that the Emmet wrap in tag function does not allow you to use attributes like the "href" in "<a href" or "class" in <div class"

**Comment by sergeche** [comment]
Just checked, everything works fine. What abbreviation you’re using for wrapping?

**Comment by dannymichel** [comment]
![screen shot 2015-01-19 at 5 40 50 am](https://cloud.githubusercontent.com/assets/1161544/5799214/c6b9546c-9f9d-11e4-80bd-df5d0ce7bd19.png)

**Comment by sergeche** [comment]
That’s not a valid Emmet expression, it should be either `li.class-name` or `li[class=class-name]`

http://docs.emmet.io/abbreviations/syntax/

**Comment by dannymichel** [comment]
Interesting. I don't mean to be a pain, but any particular reason you did it that way instead of just typing out class and having the '=' autocomplete or something?
But thanks, this works. I suppose I can get used to it.

**Comment by sergeche** [comment]
Because Emmet utilizes regular CSS selector syntax. And you can also write content into nested structures: http://docs.emmet.io/actions/wrap-with-abbreviation/

**Comment by dannymichel** [comment]
That's awesome.
