### ISSUE TITLE
Deprecated Selectors on Emmet

### ISSUE THREAD

**Issue by dinosaurfiles** [emmetio/emmet-atom#200]
>    styles/emmet.less
>        Use the `atom-text-editor` tag instead of the `editor` class.
>        Use the selector `atom-text-editor[mini]` to select mini-editors.

**Comment by jasonmelgoza** [comment]
+1

**Comment by wyongzhi** [comment]
+1

**Comment by silvenon** [comment]
I believe this was fixed in 072ae8623f76d015b439ad848ed62d583103c8a9.

**Comment by dinosaurfiles** [comment]
yep. closing it ryt now
