### ISSUE TITLE
Line-Height Output Missing "px"

### ISSUE THREAD

**Issue by jrodl3r** [emmetio/emmet-atom#201]
When attempting to use emmet shorthand for `line-height` in Atom the output is missing the "px" unit after the specified value.

![sample](http://g.recordit.co/JmK3quGmmG.gif)

**Comment by sergeche** [comment]
It’s not an issue: `line-height` may have unitless values and it’s commonly used

**Comment by jrodl3r** [comment]
That seems inconsistent w/ the other properties that do auto-populate the "px" unit postfix. For example, height and width do this automatically. Just curious as to what the reasoning is behind that difference in implementation there? Thx!

**Comment by sergeche** [comment]
There’s number of CSS properties that do not have units in their numeric values (see `css.unitlessProperties`: http://docs.emmet.io/customization/preferences/). Since `line-height` may have unitless value, forcing it to `px` will prevent you from generating unitless values at all.

**Comment by jrodl3r** [comment]
I see now, didn't realize the importance of that. Thank you :+1:

**Comment by jrodl3r** [comment]
One more noob question.. To customize this in my environment - Would I have to remove 'line-height' from `prefs.define('css.unitlessProperties', '...')` in `/lib/resolver/css.js` and then reinstall that as a custom pkg - or is there a shortcut to do this in Atom's config.json (so I can still keep getting updates, etc.)?

Thx again, really appreciate it! :beers:

**Comment by jrodl3r** [comment]
hmm.. I tried using extensions @ `~/emmet/preferences.json` w/

`{ "css.unitlessProperties": "z-index, opacity, font-weight, zoom" }`

perhaps I'm going about that the wrong way...

**Comment by sergeche** [comment]
Did you restarted Atom after creating this file? Also, you can check DevTools console for errors

**Comment by jrodl3r** [comment]
Ha! That did it... Oops! :shipit: :+1:
