### ISSUE TITLE
Expand abbreviation not working on Handlebars (.hbs) files.

### ISSUE THREAD

**Issue by rubenmoya** [emmetio/emmet-atom#204]
Hi, I'm trying to use Emmet on Handlebars files but it didn't work.

I've already tried editing my keymap.cson adding (i checked the data-attribute in the dev tools):

```
'atom-text-editor[data-grammar="text html handlebars"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

When I press tab/Cmd+E using `a` it writes `<a></a>` instead of `<a href=""></a>`

I don't know what to do so... any ideas?

Thank you.

**Comment by rubenmoya** [comment]
Ok, I fixed it adding:

````
	"handlebars": {
		"extends": "html",
		"profile": "handlebars",
		"filters": "html"
	},
```

in the `snippets.json`, and adding:

```
'atom-text-editor[data-grammar="text html handlebars"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

into the `keymap.cson`.

**Comment by mmahalwy** [comment]
@rubenmoya i cannot get your solution to work :(

**Comment by mjrev** [comment]
:+1: thanks

**Comment by jackocnr** [comment]
FYI this solved the problem for me: https://github.com/emmetio/emmet-atom/issues/83#issuecomment-71054904

**Comment by skaterdav85** [comment]
I couldn't find the snippets.json file, but simply putting the following in keymap.cson did it for me:

```
'atom-text-editor[data-grammar="text html mustache"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
'atom-text-editor[data-grammar="text html handlebars"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

(I already had one for mustache installed)

**Comment by valtlfelipe** [comment]
For newer Ember versions, this solved for me:
```
'atom-text-editor[data-grammar="text html htmlbars"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```
