### ISSUE TITLE
Snippets Tabstop

### ISSUE THREAD

**Issue by IschaGast** [emmetio/emmet-atom#216]
My snippets at Sublime Text don;t work anymore for some strange reason and that's the reason why I tried another great editor if they work over there.

This is the snippet:
````
 'ph':
      'prefix': 'ph'
      'body': '<img src=\"http://placebeyonce.com/${1:150}-${2:150}\" alt=\"${3}\" />'
````
I added this to the keymap file
````
'.pane .editor:not(.mini)':
    'tab': 'snippets:expand'
````
Otherwise I am getting this code
````
<ph></ph>
````

With the keymap solution added I get this when I type ph and tab:
````
<img src="http://placebeyonce.com/150-150" alt="" />
````

That's the right text but when I tab again the first tabstop is 150 and when I type something there it's changing but when I tab again to go to the next tabstop it looks like this:
````
<img src="http://placebeyonce.com/<hallo></hallo>-150" alt="" />
````

How can I get rid of that? It should just go to the next tabstop.

I hope that there is a simple solution for this or that this issue can be solved:
https://github.com/sergeche/emmet-sublime/issues/542

**Comment by sergeche** [comment]
They doesn’t work because Emmet overrides Tab handler. You should either extend Emmet’s snippets or re-configure full keymap for snippets: https://github.com/atom/snippets/blob/master/keymaps/snippets-2.cson

**Comment by IschaGast** [comment]
Great, that works!
Thanks a lot
