### ISSUE TITLE
Include only a subset of Emmet

### ISSUE THREAD

**Issue by silvenon** [emmetio/emmet-atom#218]
Emmet for Atom is a bit obtrusive because it overrides many existing snippets and doesn't allow new ones, so my idea was to include only a subset of Emmet.

I'm currently working on translating snippets and abbreviations from [`snippets.json`](https://github.com/emmetio/emmet/blob/master/lib/snippets.json) to an Atom-compatible snippets file, which would be used instead of `emmet:expand-abbreviation`.

So this:

```json
{
  "css": {
    "filters": "css",
    "profile": "css",
    "snippets": {
      "@i": "@import url(|);"
    }
  }
}
```

would be translated into something like this:

```json
{
  ".source.css": {
    "@i": {
      "@i": "@import url($1);"
    }
  }
}
```

I can't automatically generate meaningful snippet names, of course, but I don't think that's very important. Manually adding descriptions to snippets doesn't seem to be worth it.

This would only be the beginning, but what do you generally think of this kind of more relaxed implementation?

**Comment by sergeche** [comment]
I actually don’t understand why you need to convert dynamic Emmet snippets to static ones.
And Emmet allows you to add new snippets perfectly.

**Comment by silvenon** [comment]
For example if I add a snippet in my Atom's `snippets.cson`:

```cson
'.source.css.scss':
  '@media min-width':
    'prefix': '@min'
    'body': '@media (min-width: $1) {\n\t$2\n}'
```

Typing `@min` in an SCSS file will expand to `@media screen { }`, probably because of Emmet has some typo detecting mechanism? As I understand, Emmet requires users to add new snippets to a special `~/emmet` directory, which makes them tied to the plugin.

**Comment by sergeche** [comment]
Emmet uses fuzzy logic for expanding abbreviations: http://docs.emmet.io/css-abbreviations/fuzzy-search/
It’s a matter of better integration with editor. You can, for example, write a new method in Atom’s snippets package that populates list of matched snippets for current context and use this list in Emmet’s Tab handler.

**Comment by sergeche** [comment]
> which makes them tied to the plugin
And you can use these snippets universally across different editors. Your Atom snippets are tied to Atom editor only.

**Comment by silvenon** [comment]
> And you can use these snippets universally across different editors. Your Atom snippets are tied to Atom editor only.

Touché.
