### ISSUE TITLE
Emmet deletes line on complete and prevents tab from working

### ISSUE THREAD

**Issue by jbaxleyiii** [emmetio/emmet-atom#231]
I have recently switched back to doing front-end work and wanted my favorite package emmet back running so I could build some templates. However it seems as though I may have some conflicting package for a bug in my atom. I have removed and reinstalled emmet 5 times with no luck (both via atom, apm, and git + npm install).

Here is a gif of what is happening:
![emmet](https://cloud.githubusercontent.com/assets/4967600/6652207/e01dd89a-ca3d-11e4-91ce-55207089e452.gif)

I hit tab (or cmd + shift + e) and it deletes the text just written if it matches an emmet snippet.

Any thoughts?

**Comment by sergeche** [comment]
Please check DevTools console for errors

**Comment by jbaxleyiii** [comment]
@sergeche no errors are logged when trying to autocomplete. There is this at the top of my console:

![screenshot 2015-03-14 11 43 55](https://cloud.githubusercontent.com/assets/4967600/6652264/8b52e6e6-ca3f-11e4-8ca0-0a544cadabc3.png)

**Comment by sergeche** [comment]
What’s your Atom and Emmet versions?

**Comment by jbaxleyiii** [comment]
Atom: 0.187.0
Emmet: 2.3.4

**Comment by auxiliary** [comment]
Same for me.
Atom: 0.192.0
Emmet: 2.3.7
on Arch.

**Comment by auxiliary** [comment]
Apparently it's expecting `~/.atom/packages/emmet/lib/emmet.coffee` to exist but I have an `emmet-atom` directory instead of `emmet`. Renaming the package's directory didn't help either.

**Comment by sergeche** [comment]
One *possible* reason why it works that way is unknown document syntax. What plugin/syntax you’re using for your document?

**Comment by auxiliary** [comment]
Do you mean the document's syntax type? I tested this on an HTML.

**Comment by sergeche** [comment]
OK, HTML is fine. Can you disable all other plugins in Atom except Emmet and try again?

**Comment by auxiliary** [comment]
Hmm, It didn't help. I wonder why it looks for the emmet directory.

**Comment by sergeche** [comment]
It looks for custom Emmet extensions: http://docs.emmet.io/customization/
The only way I can help you is to connect to you via TeamViewer, can we do this?

**Comment by auxiliary** [comment]
Thanks, that would be great, but I checked this on a Mac and apparently it only happens on my Arch. So maybe it's related to the build.

**Comment by jbaxleyiii** [comment]
@sergeche @auxiliary a clean wipe of my atom install and reinstall to the latest fixed it for me. Closing issue
