### ISSUE TITLE
Emmet doesn't clean up properly after disabling it

### ISSUE THREAD

**Issue by Pizzicato** [emmetio/emmet-atom#233]
I've been having some issues with Emmet, most of them already reported, and I realized that when I try to disable the package some of them kept happening, see here:
https://discuss.atom.io/t/php-snippets-not-working/15321/7

I guess Emmet does not clean up as it should after being disabled.

Atom version: 0.187.0
Emmet version: 2.3.4

**Comment by sergeche** [comment]
Emmet cleans itself the same as Atom’s snippets package: it creates named actions which, in turn, are invoked by Atom’s keybinding resolver.

If Emmet keybindings still exists in Atom after you disable package – then it’s Atom issue

**Comment by Pizzicato** [comment]
Hi,
One of the Atom contributors and package developers thinks otherwise, have you checked the link I posted?

**Comment by sergeche** [comment]
You can turn on Keybinding Resolver package and see what action/keybinding is invoked when you hit Tab key
