### ISSUE TITLE
 PHP tags inside HTML code not highlighted if Doctype tag is present

### ISSUE THREAD

**Issue by Pizzicato** [emmetio/emmet-atom#234]
When Emmet is enabled, the  PHP tags code inside HTML are not highlighted properly if the file has the <!DOCTYPE HTML> tag or similar included. I've tried using different themes, with the same result. 

To be able to see the problem, after including DOCTYPE you have to save, close, and reopen the file, same if you take it away.

**Comment by sergeche** [comment]
Emmet has nothing to do with code highlighting.

**Comment by Pizzicato** [comment]
You're right, I've been having many problems with Atom and some packages, so I got in the "disable, restart, check, enable..." loop and got this wrong, sorry.

**Comment by Pizzicato** [comment]
here:
https://github.com/atom/language-php/issues/48
