### ISSUE TITLE
[Request] Make Emmet works in PHP files

### ISSUE THREAD

**Issue by TouPye** [emmetio/emmet-atom#240]
I often write HTML code into PHP files, but Emmet works only on HTML files.

It would be nice if we could also use Emmet in PHP files.
Or maybe add a setting to "customly add" some file types where we want Emmet to work on?

**Comment by sergeche** [comment]
I assume you’re talking about Tab key handler: https://github.com/emmetio/emmet-atom#tab-key

**Comment by TouPye** [comment]
Yes indeed.
I didn't know about that, great job! :+1:

**Comment by Yago** [comment]
@sergeche Hmmm, it don't completly resolve this issue, because with tab-key configuration, emmet works fine in PHP, but it's break atom's php completion : hiting tab after php will result `<php></php>`...

Is it just a misconfiguration on my side ?
