### ISSUE TITLE
Incorrect expanding of fsz -> font-style

### ISSUE THREAD

**Issue by pytkin** [emmetio/emmet-atom#260]
I'm using .less. `fsz` expand as `font-style`. I'm thinking this is incorrect.
##

**Comment by zackcote** [comment]
:+1:  This has been driving me insane -- it's a problem in the sublime package as well!

**Comment by beshur** [comment]
Is it posible to extend / customize this one locally?

**Comment by pytkin** [comment]
@beshur what you mean?
Problem not actual, use `fz` for **font-size** and `fs` for **font-style**.
