### ISSUE TITLE
Show CSS abbreviations in autocomplete suggestions

### ISSUE THREAD

**Issue by DaanDD** [emmetio/emmet-atom#271]
In Sublime Text, Emmet shows the available abbreviations when editing CSS files.

![screen shot 2015-05-15 at 14 23 40](https://cloud.githubusercontent.com/assets/1300724/7652598/771b8cd2-fb0e-11e4-8ba5-0c0c3dca8e99.png)

On the other hand, the same thing in Atom looks like this:

![screen shot 2015-05-15 at 14 24 11](https://cloud.githubusercontent.com/assets/1300724/7652650/fc888e2e-fb0e-11e4-84fb-a4a9f5e1e748.png)

Would it be possible to get the same functionality in the Atom version too?
##

**Comment by sergeche** [comment]
Sublime Text has API for displaying custom snippets. Atom should provide such API too

**Comment by DaanDD** [comment]
Isn't this possible with the Autocomplete Provider API described here: [http://blog.atom.io/2015/05/15/new-autocomplete.html](http://blog.atom.io/2015/05/15/new-autocomplete.html)?

It's also being requested in the official Wiki here: [https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers#providers-requested-by-the-community](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers#providers-requested-by-the-community)

**Comment by PixelT** [comment]
+1

**Comment by anrananran** [comment]
+1

**Comment by sergeche** [comment]
See https://github.com/emmetio/atom-plugin
