### ISSUE TITLE
tab/ctrl+e can't work

### ISSUE THREAD

**Issue by zeroone2005** [emmetio/emmet-atom#272]
I create a new .PHP blank file ,then input

html:5 

and press tab/ctrl+e  then it is not work.

**Comment by sergeche** [comment]
What’s your OS? Do you see any error in DevTools?

**Comment by zeroone2005** [comment]
win8.1

**Comment by zeroone2005** [comment]
but i create .html bank file ，it‘s work. 
there is not any  code of.html .php  it's bank.  
not  any error in DevTools.

sorry my English is poor.

**Comment by mrchimp** [comment]
Same here on Windows 7 using version 0.199.0. No errors in the dev tools.

**Comment by mikefrancis** [comment]
+1 same problem here for PHP and Blade (PHP templating language). Ctrl+E works but it's not as easy as just hitting tab 😔

**Comment by redgluten** [comment]
Same problem on Mac OS 10.11.1, Atom 1.2.4, Emmet 2.3.16. `Ctrl+E` works, `tab` doesn’t.

**Comment by rossuhms** [comment]
Whilst I am hesitant to bump an old issue, this is an issue that seems to have not been fixed as of yet. Is there any fix available to get tab working in .blade.php files with emmet?

**Comment by robertnicjoo** [comment]
Just go to settings->packages->{{emmet}} and select view codes
in new window select keymaps->emmet.cson and change shortcode from ctrl-e to something else such as ctrl-i

hit save and close atom next time you can use ctrl-i ;).
