### ISSUE TITLE
Allow disabling of vendor prefixing

### ISSUE THREAD

**Issue by ismay** [emmetio/emmet-atom#278]
I use autoprefixer, so I don't need automatic vendor prefixing from emmet. I would however like to use emmet for other features. Currently, it does not seem to be possible to disable just vendor prefixing, and I have to disable emmet completely. Which is a shame.

**Comment by sergeche** [comment]
See `*.autoInsertVendorPrefixes options in ` http://docs.emmet.io/customization/preferences/
And make sure you have most recent Emmet version

**Comment by ismay** [comment]
Ok, thanks.
