### ISSUE TITLE
Infinite update cycle

### ISSUE THREAD

**Issue by ZakharDay** [emmetio/emmet-atom#279]
Update in my case from 2.3.2 to 2.3.10 finished well. But on next launch Atom asking to update again. All other packages updating well.

![screen shot 2015-06-04 at 18 51 07](https://cloud.githubusercontent.com/assets/815596/7988307/6334cbba-0aeb-11e5-84f7-5b6f8a07fdf6.png)

![screen shot 2015-06-04 at 18 51 28](https://cloud.githubusercontent.com/assets/815596/7988311/6834e51e-0aeb-11e5-8010-4b802635938d.png)

![screen shot 2015-06-04 at 18 51 38](https://cloud.githubusercontent.com/assets/815596/7988313/6d35beb2-0aeb-11e5-8454-176df7c53125.png)

**Comment by sergeche** [comment]
It looks like Atom issue. Try to remove and install package again.

**Comment by ZakharDay** [comment]
It's helped. Thanks.
Strange thing... I had emmet and emmet-atom packages.
