### ISSUE TITLE
Tab open Dev Tools

### ISSUE THREAD

**Issue by martinwolf** [emmetio/emmet-atom#28]
Hey,

after installing Emmet I'm no longer able to indent anything or use the completion feature with hitting Tab. If I hit Tab, the Dev Tools open and the Syntax Mode Status is focused.
![screenshot 2014-02-27 10 33 05](https://f.cloud.github.com/assets/1442939/2280965/0294c7dc-9f95-11e3-87fc-fb8dd4b46ffb.png)

Cheers,
Martin

**Comment by thisismarco** [comment]
Great stuff! Thanks
