### ISSUE TITLE
Give the option to exclude prefixes from expanded abbreviations

### ISSUE THREAD

**Issue by varemenos** [emmetio/emmet-atom#283]
Could you please add an option in the preferences which gives us the ability to exclude prefixes from the expanded abbreviations?

**Comment by evanwarner** [comment]
+1
I want to write minimal CSS and let my build system manage prefixing.

**Comment by sergeche** [comment]
See `css.autoInsertVendorPrefixes`: http://docs.emmet.io/customization/preferences/
https://github.com/emmetio/emmet-atom#extensions-support

**Comment by evanwarner** [comment]
Ah, perfect! Made my own preferences.json file to override default Emmet settings. Thanks!
