### ISSUE TITLE
it overrides the default commenting feature

### ISSUE THREAD

**Issue by emad-elsaid** [emmetio/emmet-atom#292]
when i edit .rb files and use the "cmd+/" instead of commenting lines using "#" it uses "" 
after disabling the package it returned to normal, so i think there is a problem that makes emmet overrides the default commenting feature.
##

**Comment by jtzemp** [comment]
Same thing happens for me while I'm editing JavaScript files. Disabled emmet, and everything works normally.

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom/issues/289#issuecomment-117160655

**Comment by WesHoover** [comment]
+1 for this happening in my JavaScript files as well

**Comment by sjurba** [comment]
To enable only for html put this in your keymap.cson:
# Stop emmet from hijacking cmd-/ from non html
'.platform-darwin atom-pane atom-text-editor:not([mini])':
  'cmd-/': 'editor:toggle-line-comments'

'.platform-darwin atom-pane atom-text-editor[data-grammar="text html basic"]:not([mini])':
  'cmd-/': 'emmet:toggle-comment'

**Comment by sjurba** [comment]
But this is still a problem that needs to be fixed. At the moment, emmet breaks atom for javascript..

**Comment by RemiAWE** [comment]
+1 this is *very* annoying
