### ISSUE TITLE
`ctrl-up` same as Mission Control default keybinding in OSX

### ISSUE THREAD

**Issue by bradleyflood** [emmetio/emmet-atom#299]
By default in OSX `ctrl-up` will launch Mission Control.

I would normally use `alt-up` to increment integers by 1 in Sublime Text. Can I ask why has this shortcut been changed to `ctrl-up` in Atom? Why not keep the same as Sublime Text?

Cheers
Brad

**Comment by sergeche** [comment]
The main reason looks like this: https://github.com/sergeche/emmet-sublime/blob/master/CONTRIBUTING.md#about-keyboard-shortcuts
You can always re-map keyboard shortcuts as you wish

**Comment by bradleyflood** [comment]
Makes sense thanks.
