### ISSUE TITLE
Atom Updates will always show me that Emmet has an update available

### ISSUE THREAD

**Issue by monkeymonk** [emmetio/emmet-atom#300]
Since the Atom 1.0 release, at every start, it said that Emmet has an update... I do the update and it seems to work but at the next start -> same story ! I'm on Mac OS 10.10.4.

I put this issue in Emmet because it is the only one that make something like this.

Hope you will find a fix or providing me a workaround ! ;-)

**Comment by sergeche** [comment]
Package cannot control how Atom detects updates. You should either check if you installed Emmet twice (e.g. as dev package or something) or create issue in Atom repo

**Comment by monkeymonk** [comment]
It seems that you were right... I had 2 emmet... "emmet" and "emmet-atom". Removing the 2 and reinstall fixe the issue !

Thank you !
