### ISSUE TITLE
edit-point movement commands conflict with new core subword-boundary movement commands

### ISSUE THREAD

**Issue by menzer** [emmetio/emmet-atom#303]
As of Atom 1.0.1, ctl-alt-left and ctrl-alt-right move the cursor to the previous/next subword boundary. Emmet should probably change the keybinding so as not to conflict and override a useful core keybinding.

**Comment by MethodGrab** [comment]
:+1: I agree!
Especially on OS X where there's a duplicate binding for `emmet:next-edit-point` & `emmet:prev-edit-point` to `ctrl-left` & `ctrl-right` as well as `ctrl-alt-left` & `ctrl-alt-right`.

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime/blob/master/CONTRIBUTING.md
