### ISSUE TITLE
html:5 abbrev doesn't expand properly [$5]

### ISSUE THREAD

**Issue by trueschool** [emmetio/emmet-atom#306]
Hi--
I'm used to the ! or html:5 abbreviations in Emmet expanding to a basic HTML5 page template. The Atom plugin just encloses it in tags, like html:5/html:5.

Please see [the Emmet Cheat Sheet](http://docs.emmet.io/cheat-sheet/)

> !
>     Alias of html:5
>     <!DOCTYPE html>
>     <html lang="en">
>     <head>
>         <meta charset="UTF-8" />
>         <title>Document</title>
>     </head>
>     <body>
>     </body>
>     </html> 
##

**Comment by destos** [comment]
+1

**Comment by enebe-nb** [comment]
It works corretly here. Can you try update the atom and emmet to last version?

**Comment by adius** [comment]
Works for me too. I think this issue can be closed. Seems to be obsolete…

**Comment by FredrikAugust** [comment]
Hey,
Could you please close this issue?

No reason to be cluttering up BountySource and the issues page with this if it works like @adius and @enebe-nb says it does.
