### ISSUE TITLE
SVG Tags Are Not Recognized

### ISSUE THREAD

**Issue by grayghostvisuals** [emmetio/emmet-atom#311]
Usually I can type the tag name + tab key to auto create the opening and closing markup, but in the case with SVG this doesn't happen (works w/Emmet for Sublime).

![emmet](https://cloud.githubusercontent.com/assets/934322/8803305/2f06855e-2f94-11e5-9c6e-a5a449bdae81.gif)

**Comment by sergeche** [comment]
From your example, I can see that you’re actually expanding `autocomplete` snippets, not Emmet abbreviations.

You can check it by toggling Packages > Keybindings Resolver: the first (highlighted) item should be `emmet:expand-abbreviations-with-tab`

**Comment by grayghostvisuals** [comment]
@sergeche I found `ctrl + e` works better than your suggestion. The first highlighted item I found was what I captured in this gif. What am I doing wrong with your directions outlined?

![emmet-autocompletesvg](https://cloud.githubusercontent.com/assets/934322/8805107/6db347c0-2f9d-11e5-920d-16adc9495ee7.gif)

**Comment by sergeche** [comment]
I just proves that you’re actually expanding autocomplete snippet with Tab, not Emmet abbreviation. I this this can help you: https://github.com/emmetio/emmet-atom#tab-key

**Comment by grayghostvisuals** [comment]
@sergeche Thanks for the tips. Any chance that SVG could be more of a default rather than a customization? The end result I'd like really appreciate to see is just typing svg + tab by default would work.

**Comment by sergeche** [comment]
You can create a PR with updated scope: https://github.com/emmetio/emmet-atom/blob/master/keymaps/emmet.cson#L33

**Comment by grayghostvisuals** [comment]
So I updated the scope in `emmet.cson` to test and changed the line you linked to this…

```javascript
'atom-text-editor[data-grammar="xml text html basic"]:not([mini]), atom-text-editor[data-grammar~="jade"]:not([mini]), atom-text-editor[data-grammar~="css"]:not([mini]), atom-text-editor[data-grammar~="sass"]:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

I restarted Atom and typed `svg + tab` w/no result. I also tried changing `xml` to `svg` and ended up w/the same outcome.

**Comment by sergeche** [comment]
It’s because there’s no such grammar as `xml text html basic`. You should add a new selector, something like `atom-text-editor[data-grammar~="svg"]:not([mini])`

**Comment by grayghostvisuals** [comment]
:+1:
