### ISSUE TITLE
Expanding is not working, just removing the abbreviation instead

### ISSUE THREAD

**Issue by josser** [emmetio/emmet-atom#312]
Hi, for some reason on latest atom (1.0.2) abbreviations isn't expanded. 
When I'm pressing 'tab' or 'ctrl-e' or using 'Menu' -> Packages -> Emmet -> Expand Abbreviation it do the same thing: just removes the text of abbreviation. 

OSX 10.10.4, atom 1.0.2, emmet 2.3.12

**Comment by sergeche** [comment]
What’s your document syntax?

**Comment by josser** [comment]
just plain HTML, 

sorry for bad english :)

**Comment by sergeche** [comment]
Can you post a screenshot of editor window?

**Comment by josser** [comment]
https://www.dropbox.com/s/xcp6y7yde4vdwby/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-23%2018.27.43.png?dl=0

**Comment by sergeche** [comment]
Can you open DevTools and check if there are errors?

**Comment by josser** [comment]
No, there are no any errors in the console

**Comment by pagondel** [comment]
I think i have the same problem, when i try to expand, only the last item gets expanded:
```html
table>thead><th>
    
</th>
```

The developer tools doesn't show errors either.

**Comment by sotsy** [comment]
+1

**Comment by josser** [comment]
I have reinstalled atom without any other plugins (leaving just emmet) and everything is working now. 
So, this is probably something from other plugin. I'll investigate further and tell you which one.

**Comment by ablomen** [comment]
It seems this happens when you disable the "snippets" package and restart atom, after enabling it it seems to work again.

**Comment by David-van-den-Bor** [comment]
The last posted comment above also fixed the problem for me! I disabled the snippets package after reading that it could be the potential culprit for the TAB key not working (and deleting the line). I read the above comment, went back to Atom, enabled the "Snippets" package again, and voila!

**Comment by David-van-den-Bor** [comment]
I also changed a setting in the "Autocomplete plus" package: You can set the Autocomplete plugin to use the ENTER key to autocomplete, leaving Emmet to use the TAB key :-)

**Comment by josser** [comment]
I think it's ok to close
