### ISSUE TITLE
Doen't work on ruby

### ISSUE THREAD

**Issue by aleguarita** [emmetio/emmet-atom#315]
I'm working on Rails and the file extension is .html.erb and this package doesn't work.
On atom footer the file type appear as: <strong>HTML (Ruby - ERB)<strong>. If I change it to <strong>HTML</strong> the Emmet works again.
Please, make it works in any HTML type :)

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key
