### ISSUE TITLE
Stylus rules does not work

### ISSUE THREAD

**Issue by hmps** [emmetio/emmet-atom#326]
I prefer to use Stylus CSS syntax and I think have set the options to do so:

![site - atom 2015-08-24 20-36-49](https://cloud.githubusercontent.com/assets/1231909/9448961/e6f8866e-4a9f-11e5-9b1d-b30baf0771e0.png)

However, it is not working as expected. For example `w10p` expands to `width 10%`, I would expect the result to be `width: 10%;`.

![emmet](https://cloud.githubusercontent.com/assets/1231909/9449048/6f98928e-4aa0-11e5-94a7-6811e9b8f8cc.gif)

**Comment by droganov** [comment]
Add this to keymap:
```
'atom-text-editor[data-grammar~="stylus"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by hmps** [comment]
Thank @droganov, that helps with letting me use `tab` instead of `ctrl+e` to expand properties. Unfortunately it still doesn't solve the issue with Stylus CSS syntax.

`w10p` is still expanded to `width 10%` instead of `width: 10%;`.

**Comment by sergeche** [comment]
http://docs.emmet.io/customization/preferences/
See `stylus.propertyEnd` and `stylus.valueSeparator`

**Comment by hmps** [comment]
Thank you @sergeche. However, I have set up the `propertyEnd` and `valueSeparator` according to the screenshots in my initial issue comment.

**Comment by hmps** [comment]
Fixed by #358

**Comment by corysimmons** [comment]
@hmps Where'd you get the cool options interface for Emmet? That's Atom right?

**Comment by hmps** [comment]
Correct @corysimmons, that's Atom. And I guess it's just the Emmet settings dialog (Settings -> Packages -> Emmet -> Settings). 😄 

OT: Thank you for your great OSS work! We've used Lost quite a lot at work 👍

**Comment by corysimmons** [comment]
Ohhhhh I see. They don't show up til you add them to `config.cson`. For anyone wanting an example:

```js
// config.cson
emmet:
    stylus:
      propertyEnd: ""
      valueSeparator: ": "
```

![image](https://cloud.githubusercontent.com/assets/224636/19831018/37141ba4-9dce-11e6-87ef-dd62ba55bed9.png)

Re: OSS, teehee. Thank you. I'm glad you guys enjoy it. Launching something new soon so keep a lookout. =)

**Comment by corysimmons** [comment]
Thanks @corysimmons from the past!
