### ISSUE TITLE
Automatically select text when using Wrap with abbreviation

### ISSUE THREAD

**Issue by rabarbara** [emmetio/emmet-atom#327]
When wrapping with abbreviation the prompt gets focus but the text does not get selected.

This is in contrast with sublime text that selects the text. 

This forces me to delete the existing tags and type new ones. This is especially tedious when there are several tags listed.

Is there a way to set Emmet to automatically select the prompt text (tags) when wrapping with abbreviation?

**Comment by Dupanoodle** [comment]
I also find this tedious. It also applies to the interactive expansion also

It's much slicker in Sublime where the previously used abbreviation is hightlighted so you can just automatically type a new one or use the arrow keys to begin editing the previous one.

**Comment by rabarbara** [comment]
Fixed by [DiogoDoreto] (https://github.com/DiogoDoreto).
