### ISSUE TITLE
select previous item doesn't work

### ISSUE THREAD

**Issue by markhillard** [emmetio/emmet-atom#328]
I searched through all the issues in this repo but couldn't find anything related to my current problem. I noticed that the keybinding for `'emmet:select_previous_item'` was not checked off/completed in #1, so maybe it's just not done yet.

I'm running the latest version of Atom on Windows 7 and `'ctrl-shift-,'` is not working. If there's already an open issue where this is referenced, feel free to close this one and let me know if there's another that I should be tracking.

Thanks!
##

**Comment by markhillard** [comment]
Anyone have some kind of update on this?

**Comment by serjKim** [comment]
Your problem in conflict with key binding: 

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-<': 'editor:scroll-to-cursor'

```
You may seen that if press `ctrl+.` (Keybinding Resolver)

My quick solution:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-<': 'emmet:select-previous-item'
```
