### ISSUE TITLE
`df` Ignores Vendor Prefix Preference

### ISSUE THREAD

**Issue by MethodGrab** [emmetio/emmet-atom#336]
Atom 1.0.19 / emmet-atom 2.3.13

In Atom, if i set `"css.autoInsertVendorPrefixes": false` in my `preferences.json`, `df` (`display: flex`) will still try to expand with prefixes but `d:f` (with a colon) will expand unprefixed as expected.

![image](https://cloud.githubusercontent.com/assets/2421069/10190728/9e59411c-6766-11e5-9fb4-cc5ea0a840ae.png)

Other flex properties like `fxwn` expand correctly with & without the colon:

![image](https://cloud.githubusercontent.com/assets/2421069/10190737/aa6f4686-6766-11e5-9ad4-4491a6752781.png)

It might be related to https://github.com/emmetio/emmet/issues/401.

**Comment by yustnip** [comment]
The same issue for Stylus.

**Comment by kevinthr** [comment]
this is driving me crazy

**Comment by CodyMoore240** [comment]
Same

**Comment by sergeche** [comment]
Try to disable Can I Use in preferences as well:

```
"caniuse.enabled": false
```

**Comment by MethodGrab** [comment]
Thanks, that's fixed it!
I had `"caniuse.vendors": ""` but not `"caniuse.enabled": false`

**Comment by alistairholt** [comment]
This is driving me insane. Where do I insert `"caniuse.enabled": false`?

**Comment by bernk** [comment]
Why do `caniuse.vendors` and `caniuse.enabled` have to be disabled for this to work as expected?
