### ISSUE TITLE
Emmet don't expand for class, id and nested attributes for *.php files

### ISSUE THREAD

**Issue by Leuloch** [emmetio/emmet-atom#345]
After this last update (v.2.3.13) emmet just expand for single tags, like: `div` , `a`, `ul`, etc.

The following tags generate wrong results:

`div.row` dont expand
`div#foo` dont expand
`div>ul` expands to `div><ul></ul>`
`ul>li*5` dont expand

**Comment by chathuraa** [comment]
I'm having the same issue.

**Comment by ksr583** [comment]
Same thing here. Very frustrating when you're used to it working.

**Comment by BuddhiKasun** [comment]
same issue!

**Comment by domioanna** [comment]
Bump

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key
