### ISSUE TITLE
Emmet to Jade in Atom?

### ISSUE THREAD

**Issue by nickyhajal** [emmetio/emmet-atom#354]
I see that Emmet can output Jade but when I try in Atom, it doesn't seem to do anything. To straight HTML works fine.

Is there anyway to make this work?

Thanks!

**Comment by sergeche** [comment]
Hm, works for me. Did you set document syntax to Jade? What package are you using for Jade?

**Comment by nickyhajal** [comment]
Oy, so sorry I tried restarting and now it works great!

**Comment by Pleasurazy** [comment]
Hi, FYI

[language-jade](https://atom.io/packages/language-jade) not work

[language-pug](https://atom.io/packages/language-pug) working (pug is a new name of jade)

**Comment by datatypevoid** [comment]
Not sure yet if I should open an issue, but I am trying to use `emmet-atom` in conjunction with `pug`--used to be `jade`, as the previous poster has stated. I have the `language-pug` `atom` package installed as well, but my `emmet` snippets still compile to `html`. Is there a step I am missing in the process to enable `pug` functionality? I will kindly open another issue if needed as well.

**Comment by datatypevoid** [comment]
No amount of grammar attribute value tinkering has yielded any results either. I have tried

```
# language-specific Tab triggers
# you can add more triggers by changing `grammar` attribute values
'atom-text-editor[data-grammar="text html basic"]:not([mini]), atom-text-editor[data-grammar="text html angular"]:not([mini]), atom-text-editor[data-grammar~="erb"]:not([mini]), atom-text-editor[data-grammar~="jade"]:not([mini]), atom-text-editor[data-grammar~="pug"]:not([mini]),  atom-text-editor[data-grammar~="css"]:not([mini]), atom-text-editor[data-grammar~="stylus"]:not([mini]), atom-text-editor[data-grammar~="sass"]:not([mini]), atom-text-editor[data-grammar~="scss"]:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by denysdovhan** [comment]
I have the same issue:
![image](https://cloud.githubusercontent.com/assets/3459374/15150091/8b784c32-16d4-11e6-9d72-4d0ecfa1c0c2.png)

When I hit `Tab` with `pug` grammar I get html tags instead of pug(jade).

**Comment by 59naga** [comment]
i was solved by [atom-file-types](https://github.com/execjosh/atom-file-types#extension-matchers)

```cson
  "file-types":
    pug: "source.jade"
```
![2016-06-08 15 40 31](https://cloud.githubusercontent.com/assets/1548478/15885053/5ac34304-2d8f-11e6-80fa-df8772307706.gif)

**Comment by FabienDeborde** [comment]
@59naga  Thanks a lot for this solution !

**Comment by zhekaus** [comment]
@59naga doesn't work for me ((

**Comment by Bumboy** [comment]
I have the same problem, and the trick that  59naga  said does not work for me

**Comment by Bumboy** [comment]
Hi @zhekaus ! How did you solve these issues?

**Comment by zhekaus** [comment]
Unfortunately, not.
And it looks like there is no IDE nor editor that supports Emmet with pug yet. (
I looked into phpstorm, sublime and atom.

**Comment by Bumboy** [comment]
@zhekaus  I have found an editor that supports emmet with pug by default, it's called visual studio code, it's great give it a try, you do not need to install plugins as I said, it works by default with emmet and pug. In this youtube video there is a user using sublime text and pug, but I do not know how he did it, he does not answer the comments watch?v=HUSzqQMrHdQ For much that I look for in github and google I do not find the solution, but VScode is quite good

**Comment by lolocoo** [comment]
try to install atom-jade && use file-types, I solved this way.

**Comment by Bumboy** [comment]
file-types doesn't solve the problem

**Comment by zhekaus** [comment]
@Bumboy , thanks for vscode. I quit Atom and start using vscode for editing of pug templates. )

**Comment by LiTiang** [comment]
For guys who cant get the **_emmet_** work on **_pug_**, 
please make sure to read #458 
after do the suggestion provided as above
try install the following **_Atom_** package : 

* jade
* atom-jade
* language-jade

after the installation, restart the **_Atom_**
then the _**emmet**_ with **_pug_** should workable

**Comment by Bumboy** [comment]
@LiTiang i done your instructions, some snippets works but not "advanced" snippets for example p>div*2 doesn't work, but html (+tab) works perfectly. ! +tab doesn't work. I thought pug / jade was famous and would work well in all editors, I was wrong. Thank you anyway.

**Comment by Kagerjay** [comment]
this took way too long for me to get working, here's a painless step by step guide on how to do it assuming you don't know how to use atom

"File" can be found on topleft of screen on the ribbon menu

## 1.Install

1.  File → Settings → Install → "Search packages"
a. **Emmet** (v2.4.3)
b. **atom-jade** (v0.3.0)
c. **file-types** (v0.5.5)

## 2.Set Config

2. File → Config  (alternatively, hit <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and enter `Application: Open your config`

Paste this file at the bottom of your `config.cson` file

```
"file-types":
    pug: "source.jade"
```

![mu6lt4z 1](https://user-images.githubusercontent.com/10290348/39148084-6cf3600a-4709-11e8-81e3-32414bbc5bab.png)

## 3. Testing emmet with pug syntax

Type `link` and press <kbd>Tab</kbd>

It should do this if it works correctly

![8vaf2ac 1](https://user-images.githubusercontent.com/10290348/39148612-be2c17e0-470a-11e8-9b24-5164e0a6cccd.gif)

## NOTES

You do NOT need any packages with the name `PUG` on it for this to work

**Comment by itbro** [comment]
If it doesn't work try this:
```
"file-types":
    "*.pug": "source.jade"
```

**Comment by clg68** [comment]
Thank you! I will give it a try

CG

**Comment by brightwiths** [comment]
2019 doesn't work.
Tryed:
"file-types":
    "*.pug": "source.jade"
and 
"file-types":
    pug: "source.jade"

**Comment by brightwiths** [comment]
Finally after 2 hours, got solution.
In you use Pug, you also need use Jade code settings. 
1. Plugins: 
a. Emmet
b. atom-jade - !really important. No need to install atom-pug.
c. file-types
2. And put that in config.cson:
"file-types":
    "*.pug": "source.jade"
It will set jade syntax highlight for all new pug files.

**Comment by RixxLx** [comment]
Thank you @brightwiths 
I have also found out that you don't need file-types

Go to **Application: Open Your Config** and add the following under `core`.
```
    customFileTypes:
      'source.jade': [
        'pug'
      ]
```

One less plugin!
