### ISSUE TITLE
keybinding menu no longer shows up

### ISSUE THREAD

**Issue by vivchen** [emmetio/emmet-atom#357]
hi there,

I have the emmet package installed for Atom. At some point I may have checked off 'disable default keybindings' in the package, and now when I navigate to the settings I don't see anything in order to 'enable default keybindings' back.

Here's a pic of what I see:
<img width="1072" alt="screen shot 2015-11-23 at 11 43 22 am" src="https://cloud.githubusercontent.com/assets/2395184/11347669/687508f6-91d7-11e5-864a-faf3a59cb6d5.png">

**Comment by sergeche** [comment]
This is Emmet issue, consider Atom docs
