### ISSUE TITLE
Expand abbreviations inside an ES6/2015 template strings

### ISSUE THREAD

**Issue by wsmd** [emmetio/emmet-atom#375]
Has anyone tried to get expanding abbreviations to work inside an ES6 template string?

For example:

``` javascript
const template = `div.lovely-div|*tab*`
```

would become this

``` javascript
const tempalte = `<div class="lovely-div">|</div>`
```

The file in this case would obviously be `.js`
##

**Comment by Alcotana** [comment]
Why do you need to expand them? You can leave those abbreviations in your string and and create a function to process them. It is called a [tagged template](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals) string:

```var html = emmet`#page>div.logo+ul#navigation>li*5>a${items}`;```

Here you should write a `emmet` function, for example:
```
function emmet(strings, ...vars) {
  // Generate html
  return result;
}
```

Your string is going to be processed and the `html` var should contain smth like this:
```
<div id="page">
    <div class="logo"></div>
    <ul id="navigation">
        <li><a href="">Item 1</a></li>
        <li><a href="">Item 2</a></li>
        <li><a href="">Item 3</a></li>
        <li><a href="">Item 4</a></li>
        <li><a href="">Item 5</a></li>
    </ul>
</div>
```

**Comment by jdaroesti** [comment]
You can use ctrl+e. For example:
```js
const template = `div.lovely-div|*ctrl+e*`;
```

**Comment by RasCarlito** [comment]
The `ctrl-e` does work ! Thx @jdaroesti 

But it generates the html code as a one liner

`ul>li*2` >> `<ul><li></li><li></li></ul>`

I find it a bit problematic

**Comment by jdaroesti** [comment]
Another way is to modify your keymap with the following lines:

```
'atom-text-editor[data-grammar="YOUR GRAMMAR HERE"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

For example, I use it for Angular inline templates, so I modified it to:
```
'atom-text-editor[data-grammar="source ts"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

A more detailed explanation can be found [here](https://github.com/emmetio/emmet-atom#tab-key).
