### ISSUE TITLE
Only last element expanding.

### ISSUE THREAD

**Issue by pretzel80** [emmetio/emmet-atom#381]
Possibly similar to [issue 345](https://github.com/emmetio/emmet-atom/issues/345):
In a list of nested elements, only the last element expands when hitting tab.
Example:

`table.class>th+tr`

expands to:

`table.class>th+<tr></tr>`

Happens to me in both *.php and *.html files.  My current plugin version is 2.3.17

Edit: Alright, NOW it seems to be working with *.html files - so probably a dupe of #345.

**Comment by BuddhiKasun** [comment]
same issue!

**Comment by domioanna** [comment]
Bump

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key
