### ISSUE TITLE
Option "css.autoInsertVendorPrefixes" doesn't work

### ISSUE THREAD

**Issue by in-in** [emmetio/emmet-atom#385]
I created the `preferences.json` file and put it in `~/emmet` directory. But nothing has changed. 
`df ` and `d:f` still expand with vendor-prefixes.

![fail](https://cloud.githubusercontent.com/assets/8797432/12329148/f7aea932-baef-11e5-945e-cbbf9c5db352.jpg)

Atom: version 1.4.0
Emmet-atom: version: 2.3.17
System: Ubuntu 14.04

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#extensions-support

> By default, it’s ~/emmet, e.g. emmet folder in your system HOME folder.
