### ISSUE TITLE
Snippets no longer working since v2.4.0

### ISSUE THREAD

**Issue by caleb531** [emmetio/emmet-atom#388]
Hi,

I recently created a series of Emmet snippets for SVG (since I hand-craft many of the SVGs I use). These snippets are located in my Emmet extensions directory in `snippets.json`.I know the Emmet is reading from the extensions directory correctly, since 1) this was all working fine the other day, and 2) my Emmet preferences are correctly read and applied.

However, today I discovered that my snippets are no longer functional—it's as if they never existed. My HTML and CSS preferences are still applying, and my syntax profiles are also correctly applied. Considering that everything was working perfectly yesterday, I suspect v2.4.0 (which was released only 13 hours ago) must be the cause of this bug. After downgrading to v3.3.18, the snippets work again.

I am using the [language-svg](https://github.com/erikdahlstrom/language-svg) package for SVG grammar.

Here is my `snippets.json` file.

```json
{
  "php": {
    "extends": "html",
    "profile": "php",
    "abbreviations": {
      "foo": "<foo bar=\"\" />"
    }
  },
  "svg": {
    "profile": "svg",
    "abbreviations": {
      "circle": "<circle cx=\"\" cy=\"\" r=\"\" />",
      "clipPath": "<clipPath id=\"\">",
      "ellipse": "<ellipse cx=\"\" cy=\"\" width=\"\" height=\"\" />",
      "line": "<line x1=\"\" y1=\"\" x2=\"\" y2=\"\" />",
      "mask": "<mask id=\"\">",
      "path": "<path d=\"\" />",
      "pattern": "<pattern id=\"\" x=\"\" y=\"\" width=\"\" height=\"\" patternUnits=\"userSpaceOnUse\">",
      "polygon": "<polygon points=\"\" />",
      "polyline": "<polyline points=\"\" />",
      "rect": "<rect x=\"\" y=\"\" width=\"\" height=\"\" />",
      "svg": "<svg viewBox=\"\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">",
      "use": "<use xlink:href=\"\" x=\"\" y=\"\" />"
    }
  }
}
```

Thanks,
Caleb

**Comment by sergeche** [comment]
Just pushed v2.4.1, should fix this issue

**Comment by caleb531** [comment]
Yep, v2.4.1 fixes the issue. Thanks very much for the quick fix!
