### ISSUE TITLE
Emmet expansion deleting text

### ISSUE THREAD

**Issue by yoniholmes** [emmetio/emmet-atom#389]
I'm not sure what's happened, but Emmet appears to be failing entirely, by deleting the matched expansion text whenever I try to expand it. 

On my mac, in a given file, such as 'index.html', when I type something like:   `div.hello`, I then do one of the following:  click `tab`, `cmd`+`shift`+`e`, `ctrl`+`e`, `cmd`+`shift`+`p` then select 'Emment: Expand Abbreviation', the result is that `div.hello` is deleted, instead of converting it to: `<div class=""hello"></div>`.

The same behaviour is happening in CSS files, i.e. matches are being deleted instead of expanded.

I'm on OS X 10.10.5 (Yosemite), Atom 1.4.0, and Emmet-atom 2.4.1 (I tried 2.4.0 before, and 2.4.1 which was released 12 minutes ago). 

I'm sure it's related to Emmet, because when I disable emmet clicking `tab` results in a regular tab character as I would expect. Enabling Emmet causes the problem to recur, consistently. Furthermore when I view the Key Binding Resolver, I see that emmet:expand-abbreviation-with-tab is called. 

For now Emmet is unusable, so I need to switch it off. Please can someone try to replicate this or fix this as a priority?

Many thanks, 

Jonathan

**Comment by sergeche** [comment]
Check out DevTools console, do you see any errors?

**Comment by yoniholmes** [comment]
Thanks for the prompt reply. When trying the above, there is no output at all within the dev tools.

**Comment by sergeche** [comment]
what’s your Emmet version?

**Comment by yoniholmes** [comment]
As stated in the comment, it's now at 2.4.1. The error was also occurring in previous versions (2.4 and I believe 2.3.x)

**Comment by sergeche** [comment]
Oh, I see it’s 2.4.1. Do you have any custom Emmet extensions? What’s your document syntax?

**Comment by yoniholmes** [comment]
I'm currently editing an HTML file. The syntax is set to 'HTML'

**Comment by sergeche** [comment]
Is it possible to connect via TeamViewer so I can see it by myself?

**Comment by yoniholmes** [comment]
There is one other factor which might be important. I was previously editing handlebars files (*.hbs). I wanted for emmet to expand the HTML that I wrote in those files. I attempted to add handlebars in my keycap.cson by following some instruction I found online (can't find the link). I *think* the errors started then. I deleted the line in the same keycap.cson but the errors haven't gone away.

**Comment by yoniholmes** [comment]
Am on a work machine, so won't be able to use TeamViewer am afraid

**Comment by sergeche** [comment]
Does Emmet works with other syntaxes? Like CSS, XML

**Comment by yoniholmes** [comment]
In CSS files again text which should be matched by Emmet is getting deleted instead of expanded

I tried to create an xml file, but it appears that Emmet is not taking any effect there. Ie. clicking 'tab' results in the tab character being entered. But then, I don't know Emmet's expansion rules for XML files.

**Comment by yoniholmes** [comment]
It appears that Emmet is clearing executing the 'expand-abbreviation' command, but the result of running it is an empty string rather than the correct expansion.

**Comment by sergeche** [comment]
Do you have custom Emmet snippets or something? Can you show a full DevTools log after Atom starts?

**Comment by yoniholmes** [comment]
Not sure I know how to get the full log, other than opening the dev tools once Atom has loaded. Doing that I find the following:

```
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Users/[my user name]/.atom/packages/emmet/lib/emmet.coffee:139 Loading Emmet extensions from ~/emmet
/Users/[my user name]/.atom/packages/emmet/lib/emmet.coffee:156 Emmet: no such extension folder: /Users/[my user name]/emmet
index.js:52 Window load time: 1825ms
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:915 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

Looks like we're on to something though, it not being able to find the extension folder? Any ideas how to resolve this?

**Comment by yoniholmes** [comment]
I don't have any custom Emmet snippits though.

**Comment by sergeche** [comment]
No, it’s not a problem, it simply notifies that there’s no extension folder. I’m afraid I can’t help without TeamViewer

**Comment by yoniholmes** [comment]
So I went for the nuclear option. I deleted my ~/.atom directory, and in doing so removed all installed plugins and settings. However, when I reinstall emmet I can now successfully expand abbreviations. Thanks for your help trying to debug this though. While you're here I don't suppose you're able to say how I might be able to add `\*.hbs` files to Emmet's HTML expansion? I realise this is off topic from the original bug, but I'm happy for the bug to be closed now. Many thanks, Jonathan

**Comment by sergeche** [comment]
I wrote about Tab handler issues here: https://github.com/emmetio/emmet-atom/issues/108#issuecomment-173551501

**Comment by yoniholmes** [comment]
Ok thanks Sergey.

**Comment by uchsarath** [comment]
Thank you so much @jbotos that work pretty fine. Awesom.e

**Comment by eternal-sorrow** [comment]
had the same issue

**Comment by eternal-sorrow** [comment]
by some experiments I found out that it's caused bu disabling core snippets package

**Comment by tiffanytse** [comment]
For those that find this issue and are looking for a fix: 

Go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
 
```
'atom-text-editor:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by AzureByte** [comment]
I did not have the core snippets package disabled but had disabled Emmet. I found I had to delete this 'fix' line for tab to work again.

> 'atom-text-editor:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
