### ISSUE TITLE
Emmet doesn't work on PHP file!

### ISSUE THREAD

**Issue by huyle2607** [emmetio/emmet-atom#393]
As in the title of the Issue, I cannot use emmet in PHP file. I don't know why but it seems to work well on only html file.
Is there any way to make it works on file .php?
If you could do it, I would appreciate it!

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by RafiKueng** [comment]
Add this to your `keymap.cson` file (ctrl+shift+p "open keymap")

    'atom-text-editor[data-grammar="text html php"]:not([mini])':
        'tab': 'emmet:expand-abbreviation-with-tab'

Would be nice to make it default thou...

**Comment by SiidySilva** [comment]
@RafiKueng very good (y)

**Comment by medBouzid** [comment]
@RafiKueng Awesome it works! thanks.

For those who are using laravel then add blade as well :   
```

'atom-text-editor[data-grammar="text html php blade"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by tjhillard** [comment]
Awesome - but now when I ```div.container``` it completes to ```<div className="container"</div>```.  I don't want the className, how do I change it back?

**Comment by renoirfaria** [comment]
Guys, i solved the problems related to this issues by using this extra atom package.

https://atom.io/packages/emmet-snippets-compatibility

**Comment by fluxish** [comment]
@medBouzid sorry, but with `data-grammar="text html php blade"` now works with blade but no more with php files... why?

**Comment by mikael1000** [comment]
@scratchoo

With your solution I get very strange results. For example:

`.col -> .<col span="2">` expected: `<div class="col"></div>`
`.row -> .BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va` expected: `<div class="row"></div>`

On other things I don't get anything. Just a tab.

When I google the strange string (result from .row) it turns out to be part of the integrity key from MaxCDNs bootstrap link. How did that get connected to the `.row` command?

However if I just remove "blade" from the code it works in blade, php, html files.

**Comment by coollorenzo** [comment]
Are there any plans to make this the default behaviour?

**Comment by sergeche** [comment]
Upcoming Emmet 2.0 will have some defaults like this

**Comment by blackwood00** [comment]
> Add this to your `keymap.cson` file (ctrl+shift+p "open keymap")
> 
> ```
> 'atom-text-editor[data-grammar="text html php"]:not([mini])':
>     'tab': 'emmet:expand-abbreviation-with-tab'
> ```
> Would be nice to make it default thou...
this solution works on me perfectly .. the thing that you all have to do is,

step 1 :  (ctrl+shift+p) and enter "keymap.cson" on search bar.
step 2 :  just copy code belllow as it is and make sure to do nothing else.
 
```
'atom-text-editor[data-grammar="text html php blade"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```
step 3 : save the code (keymap.cson). 
step 4 : restart atom. (if you need).
step 5 : enjoy ...

**Comment by robertbossaert** [comment]
If anyone else stumbles upon this problem and the above solutions do not work on your php file; I had to change it to this:

`'atom-text-editor[data-grammar~="php"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'`

note the `~`

**Comment by raedlime** [comment]
solved the problem w/ @robertbossaert solution – thx mate!
