### ISSUE TITLE
Shift-space is too easy to accidentally press

### ISSUE THREAD

**Issue by jrial** [emmetio/emmet-atom#404]
The standard shift+space keybinding is too easy to press accidentally; when writing in all caps, not everyone uses caps lock. When holding down shift while typing caps words, every word is turned into an XML tag because of this.

A better key binding would be welcome.
##

**Comment by Maarx** [comment]
:+1:

**Comment by greencopper** [comment]
I agree 100% In Vim, medit, and lots of other editors, holding SHIFT while pressing spacebar will simply make a space. It's really annoying that SHIFT "locks" the spacebar. Lets get another keybinding and release shift+space for just space!

**Comment by greencopper** [comment]
Updated to BETA and problem solved.

**Comment by pedzed** [comment]
God, this is annoying!

Any updates on this?

**Comment by sergeche** [comment]
Don’t know what kind of Shift-space problem this issue about, there’s no such keybinding: https://github.com/emmetio/emmet-atom/blob/master/keymaps/emmet.cson

**Comment by jrial** [comment]
You're right. I must've filed this issue under the wrong package. Closing.

**Comment by jrial** [comment]
Found the culprit. It was not emmetio/emmet, but peterjohnhunt/emmet-snippets-compatibility so I'll file it there instead. Sorry for the nuisance.

**Comment by sergeche** [comment]
Note that there’s no need in such packages with new Emmet 2.0: https://github.com/emmetio/atom-plugin
