### ISSUE TITLE
Self-closing tag

### ISSUE THREAD

**Issue by hansokumake** [emmetio/emmet-atom#408]
How can I configure emmet package to generate self-closing tags for HTML documents?
##

**Comment by brunowego** [comment]
I get this small issue when I try autocomplete a `img` tag:

![issue](https://cloud.githubusercontent.com/assets/441774/13643789/49d451ee-e601-11e5-8e13-3c86eec76c56.gif)

**Comment by ccqgithub** [comment]
I have the same trouble  ...

**Comment by mpolichette** [comment]
I use emmet for writing JSX and it would be really cool if emmet would let use cycle through the forms.
E.G. repeatedly hitting `ctrl+e` would cycle as such:
`MyComponent` -> `<MyComponent></MyComponent>` -> `<MyComponent />` -> `MyComponent`

I think this would make it really simple to learn/discover the feature also.

**Comment by huarse** [comment]
+1, @mpolichette 's suggest is a good idea.

**Comment by mpolichette** [comment]
For what it's worth, I use prettier in my projects now, and it will close tags automatically for me... so generating a self closing tag is less of a big deal. 

This still would be a nice feature since I often need to open them to add content and a cycle would hopefully allow that...

**Comment by sergeche** [comment]
The new Emmet 2.0 beta supports self-closing slash in abbreviations, e.g. `MyComponent/` → `<MyComponent />`
See http://github.com/emmetio/atom-plugin

**Comment by mugukamil** [comment]
@sergeche where I can download Beta Emmet? Now I have 2.4.3 and its not working `Header/` - just nothing happen...

**Comment by huarse** [comment]
@sergeche the same question with upstairs

**Comment by sergeche** [comment]
There’s a link right in comment: http://github.com/emmetio/atom-plugin

**Comment by nextriot** [comment]
Is there a 2.0 beta available for Sublime? I haven't seen this feature in production yet (not even in VSCode)

**Comment by sergeche** [comment]
Sublime version is not available yet and VSCode has buggy implementation of this feature
