### ISSUE TITLE
Keyboard shortcuts have disappeared

### ISSUE THREAD

**Issue by c10b10** [emmetio/emmet-atom#413]
In Atom 1.6.0 Emmet version 2.4.3 it seems that keyboard shortcuts have disappeared, and custom mappings have stopped working. Searching for emmet in the Keybindings view reveals nothing.

This is how the settings page for the plugin looks.
<img width="1019" alt="screen shot 2016-03-21 at 19 33 49" src="https://cloud.githubusercontent.com/assets/306633/13927826/fb8da978-ef9b-11e5-8be6-a5d710943413.png">

**Comment by sergeche** [comment]
That’s strange. Can you remove Emmet extension and install again? Also you can check out DevTools for possible errors

**Comment by c10b10** [comment]
I tried reinstalling both ways (atom UI and apm), no effect.

Dev tools does reveal some issues. Take a look:

<img width="1435" alt="screen shot 2016-03-21 at 22 43 24" src="https://cloud.githubusercontent.com/assets/306633/13933570/82377b9c-efb6-11e5-9434-ffe108aec273.png">

**Comment by sergeche** [comment]
Emmet looks fine but I see there are errors in core Atom. Don’t know if it’s a cause of your issue. Are there similar issues with other packages?

**Comment by c10b10** [comment]
Emmet seems to be the only one.

**Comment by MaximRouiller** [comment]
On my end, CTRL-E stopped working. After activating the key binding resolver, it seems that the `find-and-replace:use-selection-as-find-pattern` is being used instead. 

![image](https://cloud.githubusercontent.com/assets/209384/13952902/7fa4104e-f00f-11e5-8875-089a745dce8a.png)

I will try to uninstall/install the package again.

**Comment by MaximRouiller** [comment]
Deactivating and reactivating the keybindings solved the issue for me.

![image](https://cloud.githubusercontent.com/assets/209384/13952937/b1286c82-f00f-11e5-8ccc-6c0588afeb0f.png)

**Comment by MaximRouiller** [comment]
Issue with the upgrade I guess?

**Comment by c10b10** [comment]
Seems that none of the custom keybindings are loaded on my end as well. Deactivating and reactivating the keybindings resolver did not solve the issue.

**Comment by c10b10** [comment]
It seems that there was an issue with the atom `keymap.cson` definitions.

```cson
'atom-text-editor.vim-mode-plus:(.insert-mode)':
  'ctrl-w h': 'window:focus-pane-on-left'
  'ctrl-w l': 'window:focus-pane-on-right'
```

`silently` failed because the `not` was missing before the `(.insert-mode)`.
