### ISSUE TITLE
Emmet fails everywhere

### ISSUE THREAD

**Issue by Marecages** [emmetio/emmet-atom#435]
Hello team,

I notice problems with emmet.
when I type _ul>li_, I get (by tab) : 

 ul><'li><'/li>*
*without " ' " => code is interpreted

when I type _nav>section.sth_ OR  _article.sth_
it does nothing (a tab)

I thought it were some conflicts with my installed packages, but when I disable it, the bug persists.

Any idea about that problem ?
Thanks.

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by Marecages** [comment]
Sorry, OK, I didn't see this.
But it helps me not completely : how can I open "DevTools"?

**Comment by Marecages** [comment]
Sorry, I didn't see this. Thank you very much.
