### ISSUE TITLE
Doesn't work inside a php function

### ISSUE THREAD

**Issue by yassersharaf** [emmetio/emmet-atom#438]
Hi
inside html page it works fine but not inside a php function with php autocomplete packages are installed
a.logo then tab doesn't do anything but just a tab but inside html page the result is
<a class="logo"></a>

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#readme

**Comment by yassersharaf** [comment]
I'm writing it as html not as php
function test(){
?>
a.logo -> Tab
<?php
}
and what is grammar
'atom-text-editor[data-grammar="YOUR GRAMMAR HERE"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
