### ISSUE TITLE
Emmet isn't working properly whenever I install the Angular JS Package. 

### ISSUE THREAD

**Issue by ray-o** [emmetio/emmet-atom#446]
Emmet started acting funny when I installed the AngularJS package to speed up productivity.
Whenever I type commands and press tab they either don't give the correct output or just don't work at all.

Example:

ul>li*5 = nothing

input =  <input type="button" name="name" value=""> instead of  the default <input type="text">

even when I specifically type input:c for a checkbox it gives me = input:<canvas id="canvas" width="300" height="300"></canvas>

or input:checkbox = nothing

Once I disabled the AngularJS package and  restarted Atom Emmet went back to normal.

Would this be considered a bug?

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by ray-o** [comment]
Solved the issue by pasting this into keymap.cson

'atom-text-editor[data-grammar="text html angular"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
