### ISSUE TITLE
</ not closing HTML tag

### ISSUE THREAD

**Issue by fishcharlie** [emmetio/emmet-atom#450]
So in an HTML document I could have sworn that typing </ will automatically close the open HTML tag in Emmet. I could be totally wrong about this.

But for some reason in Atom that shortcut no longer works. Any ideas?

**Comment by sergeche** [comment]
It’s a Sublime Text feature, not Emmet’s

**Comment by fishcharlie** [comment]
Hmm ok. I could have sworn it was working in Atom in the past. Maybe I will make a bug report on Atom. Thanks.
