### ISSUE TITLE
Emmet doesn't finish my tags after pressing Tab

### ISSUE THREAD

**Issue by xXxtraCookie** [emmetio/emmet-atom#455]
Hello,

I don't know the reason but since the installing of Emmet it doesn't finish the tags I write after pressing Tab button. I viewed the settings and the Tab button was on for finishing commands. Can you please help me fix my problem because your tool is so amazing and I can't use any of it :(
Thank you very much in advance!

Best Regards,
Peter Kolev.

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by Iyashu5040** [comment]
I'm having the same issue in Sublime Text 3, in HTML. "foo" + tab only inserts a tab character. "foo*1" + tab creates <foo></foo> tags as expected.

**Comment by sergeche** [comment]
@Iyashu5040 https://github.com/sergeche/emmet-sublime#tab-key-handler
