### ISSUE TITLE
PUG don't work

### ISSUE THREAD

**Issue by WhiteLeash** [emmetio/emmet-atom#458]
When I try use emmet with PUG it doesn't work, with JADE works fine but not with PUG.
I can't use ! + TAB for make simple structure and other things :/ 
##

**Comment by Antlitz** [comment]
same prob.

**Comment by aazcast** [comment]
Same here using sublimetext 3

**Comment by tameemsafi** [comment]
I am having the same issue.

**Comment by GriNAME** [comment]
Same the problems

**Comment by gurdilou** [comment]
Same here

**Comment by itslooklike** [comment]
same, not working 🤒

**Comment by artdevjs** [comment]
+1

**Comment by siakas** [comment]
Same the problems

**Comment by JustineWin** [comment]
I think emmet is not yet updated and doesn't support pug as of now.

**Comment by sergeche** [comment]
I’m in the middle of full Emmet rewrite. Pug support will be added into new version

**Comment by GriNAME** [comment]
It's a good news!

**Comment by zhekaus** [comment]
+1

**Comment by WhiteLeash** [comment]
Yey :D

**Comment by mdmad7** [comment]
patiently waiting

**Comment by mdmad7** [comment]
Found this fix.
[Install atom-file-types](https://atom.io/packages/file-types).
Open the config file. Atom-->Config.
Paste the code below in the config file. this should work
"file-types":
    pug: "source.jade"

**Comment by GriNAME** [comment]
And is it working?

**Comment by mdmad7** [comment]
yup...100%

**Comment by GriNAME** [comment]
wow! I went to try it)

**Comment by mdmad7** [comment]
<img width="689" alt="screen shot 2017-01-07 at 4 41 48 pm" src="https://cloud.githubusercontent.com/assets/9369671/21743320/9c790a4e-d4f7-11e6-8443-de2666275ec7.png">
<img width="687" alt="screen shot 2017-01-07 at 4 39 33 pm" src="https://cloud.githubusercontent.com/assets/9369671/21743321/9ca146d0-d4f7-11e6-9988-ccb1ca48fffa.png">

Attached images of my config file and .pug file demoing it working.

**Comment by zhekaus** [comment]
I tried this workaround and It didn't work for me

**Comment by Bumboy** [comment]
I have the same problem, and the trick that mdmad7 said does not work for me either

**Comment by sergeche** [comment]
For those who’s not afraid of testing new things, check out first alpha version of new Emmet plugin (Pug support included): https://github.com/emmetio/atom-plugin

**Comment by LiTiang** [comment]
For guys who cant get the **_emmet_** work on **_pug_**, 
please make sure to read #354 
after do the suggestion provided as above
try install the following **_Atom_** package : 

* jade
* atom-jade
* language-jade

after the installation, restart the **_Atom_**
then the _**emmet**_ with **_pug_** should workable

**Comment by Bumboy** [comment]
@LiTiang i done your instructions, some snippets works but not "advanced" snippets for example p>div*2 doesn't work, but html (+tab) works perfectly. ! +tab doesn't work. I thought pug / jade was famous and would work well in all editors, I was wrong. Thank you anyway.

**Comment by mdmad7** [comment]
Honestly don't get y urs arent working.  if u still wanna give it a shot, try installing dese plugins as well,
atom-pug
language-pug

Lemme noe wat happens
