### ISSUE TITLE
Doesn't expand html tags in HTML(ASP) files #

### ISSUE THREAD

**Issue by rulehial** [emmetio/emmet-atom#463]
I assume the scope is set not to expand html e.g.

`div.foo`
to
`<div class="foo"></div>`

in .asp files. Is there anywhere I can add .asp files to the scope?

in sublime text it solved
https://github.com/sergeche/emmet-sublime/issues/98

thanks

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by rulehial** [comment]
great add this line in emmer.cson and everything works great

`atom-text-editor[data-grammar="text html asp"]:not([mini])`
