### ISSUE TITLE
Where to add these setting as mention this article but for sublime ?

### ISSUE THREAD

**Issue by jitendravyas** [emmetio/emmet-atom#467]
https://pawelgrzybek.com/bem-with-emmet/

```
{
  "syntaxProfiles": {
    "html" : {
      "filters" : "html, bem"
    }
  },
  "preferences": {
    "bem.elementSeparator":"__",
    "bem.modifierSeparator":"--",
    "bem.shortElementPrefix":"-"
  }
}
```

**Comment by nicothin** [comment]
+1

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#extensions-support

**Comment by nicothin** [comment]
@sergeche 
У меня настройки все равно не подхватываются :(
Extensions path в настройках Atom у меня по умолчанию: `~/emmet`
Я в винде, так что это у меня `c:\Users\nicothin\emmet\`, кладу в эту папке файл `preferences.json`, в котором:
```
{
  "bem.elementSeparator": "__",
  "bem.modifierSeparator": "--",
  "bem.shortElementPrefix": "_",
  "css.autoInsertVendorPrefixes": "false",
  "lorem.defaultLang": "ru",
}
```
Перезапускаю Atom.
Проверяю на `lorem` — разворачивается латинская «раба».
Что я сделал не так?

**Comment by sergeche** [comment]
Если файл именно в таком виде, то это невалидный JSON, в конце запятая не нужна

**Comment by jitendravyas** [comment]
Please use english so I can also understand ;-)

**Comment by jitendravyas** [comment]
Please use English if possible so I can also understand :-)

**Comment by sergeche** [comment]
The provided example is invalid JSON so it can’t be parsed and loaded by Emmet

**Comment by nicothin** [comment]
Sorry for carelessness!
