### ISSUE TITLE
Disable vendor prefixing

### ISSUE THREAD

**Issue by wldcordeiro** [emmetio/emmet-atom#470]
I've tried doing this a number of ways now, but none seem to be respected. What do you add to your `config.cson` to disable this?
##

**Comment by DavidBachmann** [comment]
I've been fighting this for an hour and managed to disable it.

Create preferences.json in ~/emmet (Create the emmet folder if it does not exist.)

```
{
 “caniuse.enabled”: false
}
```

Restart atom

**Comment by lbineau** [comment]
Thank you @DavidBachmann! Struggled a lot with this issue. I've been tried the following without succes.
```json
{
"css.autoInsertVendorPrefixes": false
}
```

**Comment by tlockAOB** [comment]
@DavidBachmann this solution did not work for me. Any idea how I can troubleshoot further?
