### ISSUE TITLE
Trigger emmet only inside the render function part - React/JSX

### ISSUE THREAD

**Issue by ericdouglas** [emmetio/emmet-atom#484]
First of all, thank you so much for this really helpful package! :smile: 

One feature that would be really nice to have is [this](http://wesbos.com/emmet-react-jsx-sublime/) [one](https://gist.github.com/wesbos/2bb4a6998635df97c748). Something like `meta.group.braces.round.js`:

```json
{
    "context": [
        {
            "operand": "meta.group.braces.round.js", 
        }
    ]
}
```

Also asked [here](https://github.com/emmetio/emmet-atom/issues/237#issuecomment-193426731), [here](https://github.com/emmetio/emmet-atom/issues/237#issuecomment-247366802) and [here](https://github.com/emmetio/emmet-atom/issues/237#issuecomment-235246909).

:pray:

**Comment by sergeche** [comment]
I’m in the middle of full Emmet rewrite right now, will address this issue for React as well in different manner

**Comment by ericdouglas** [comment]
@sergeche awesome, many thanks! :smile:
