### ISSUE TITLE
Not working with .erb files

### ISSUE THREAD

**Issue by RigoTheDev** [emmetio/emmet-atom#500]
With Atom's Ruby on Rails package, you have a shortcut where you can just tab `- ` & `=` and they turn into `<%  %>` & `<%=  %>` respectively.
It's pretty useful. But when I installed Emmet & I tried using my usual Rails shortcuts it just doesn't work anymore. It just turns into `<-> </->` or nothing at all for `=`.
I don't know if there's a way to disable tab completion for specific tags.

**Comment by sergeche** [comment]
Please try new Emmet 2 plugin (currently in alpha): https://github.com/emmetio/atom-plugin

**Comment by cmwinters** [comment]
I was about to open this same issue. Thank you @sergeche! Emmet 2 seems to work great so far...

**Comment by foliwe** [comment]
I installed the Emmet 2 plugin but can still get the rails `<% %>` & `<%= %>` to work
