### ISSUE TITLE
Tab doesn't work

### ISSUE THREAD

**Issue by basilalex** [emmetio/emmet-atom#503]
Hi, just installed atom and find that I can't TAB, can't expand even by shift+cmd+e, it deletes the word. If I disable the emmet package, TAB works well.

**Comment by YikaJ** [comment]
It happens on me too

**Comment by tiffanytse** [comment]
If you find after installing emmet tab completion doesn’t work as described in the documentation, go to Atom > Keymap add the following code, then restart Atom (this fix worked for me):
 
```
'atom-text-editor:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by dannycolin89** [comment]
> If you find after installing emmet tab completion doesn’t work as described in the documentation, go to Atom > Keymap add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

It doesn't work for me :/

**Comment by 12Aleks** [comment]
Super, it works. Thank you

**Comment by DinoVas** [comment]
Worked for me as well. Thanks a lot.

**Comment by ZinMar91** [comment]
Worked well. Thanks!

**Comment by yogain123** [comment]
Worked for me as well. Thanks !!!

**Comment by mpwashburn** [comment]
Worked for me! Thank you.

**Comment by ssssct** [comment]
Works for me, thanks !

**Comment by vikram-rawat** [comment]
Is this how I am supposed to insert it.

because it didn't work for me

![image](https://user-images.githubusercontent.com/22342596/35030047-bbcec93e-fb83-11e7-845d-c45b9ab1ca1a.png)

**Comment by rebecasouza** [comment]
@vikram-rawat just copy and paste what @tiffanytse posted instead. Super worked for me. Thanks a bunch!

**Comment by almightyolmec** [comment]
@tiffanytse Thanks. It worked perfectly.

**Comment by sebastianks** [comment]
If anyone still have issues with this, consider doing what Emmet tells you to: https://atom.io/packages/emmet under "Tab key". I had to do this for Vue files for example, because I am writing scss inside the .vue file.

**Comment by gitlet** [comment]
Hey @tiffanytse ! Awesome, thanks it worked for Me!!

**Comment by enviso** [comment]
@tiffanytse worked, thanks!

**Comment by thavoo** [comment]
@tiffanytse great it worked for me thanks :+1:

**Comment by ERROPiX** [comment]
This is not a solution, as it will prevent auto-complete of other languages and packages

**Comment by tomtusz** [comment]
@tiffanytse  It worked, thanks!

**Comment by duza-two** [comment]
It worked for me thanks 😃

**Comment by m2maomao** [comment]
thanks!,I follow your code,It's worked now!

**Comment by amzakil** [comment]
I can't find the Atom> Key map. There's no Atom in my menu.

**Comment by krekto** [comment]
@amzakil file>keymap ..

@tiffanytse worked here, tx

**Comment by Hadeeskyu** [comment]
> > If you find after installing emmet tab completion doesn’t work as described in the documentation, go to Atom > Keymap add the following code, then restart Atom (this fix worked for me):
> > ```
> > 'atom-text-editor:not([mini])':
> >   'tab': 'emmet:expand-abbreviation-with-tab'
> > ```
> 
> It doesn't work for me :/
> 
> **Update**
> Duplicate of #478

thanks alot

**Comment by Hadeeskyu** [comment]
> If you find after installing emmet tab completion doesn’t work as described in the documentation, go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

thanks bro

**Comment by A-D-E** [comment]
Thanks a lot!

**Comment by leshiq** [comment]
thx

**Comment by Steve-Hsu** [comment]
if you guys tried @tiffanytse 's solution and doesnt't work, 
Try this package "emmet-snippets-compatibility"
https://atom.io/packages/emmet-snippets-compatibility

Before install the package, remember to delete the code you paste on  Keymap.
it worked for me.

**Comment by Aegontar** [comment]
It worked for me :)

**Comment by mertysr** [comment]
> > If you find after installing emmet tab completion doesn’t work as described in the documentation, go to Atom > Keymap add the following code, then restart Atom (this fix worked for me):
> > ```
> > 'atom-text-editor:not([mini])':
> >   'tab': 'emmet:expand-abbreviation-with-tab'
> > ```
> 
> It doesn't work for me :/
> 
> **Update**
> Duplicate of #478

It worked for me.  Thanks a lot.

**Comment by mertysr** [comment]
> If you find after installing emmet, tab completion doesn’t work as described in the documentation, go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

It worked for me. Thanks a lot.

**Comment by dr3apap** [comment]
got this error when I tried to use the code for keymap, I tried more than 5 times emmet still not working.

stdin]:35:10: error: missing '
  'tab': 'emmet:expand-abbreviation-with-tab
         ^

**Comment by virgildotcodes** [comment]
> if you guys tried @tiffanytse 's solution and doesnt't work,
> Try this package "emmet-snippets-compatibility"
> https://atom.io/packages/emmet-snippets-compatibility
> 
> Before install the package, remember to delete the code you paste on Keymap.
> it worked for me.

Thanks, tried everything else listed here, and this was what worked for me!

**Comment by only1dallas** [comment]
awesome! thanks.

**Comment by CriticalWill** [comment]
> 
> 
> if you guys tried @tiffanytse 's solution and doesnt't work,
> Try this package "emmet-snippets-compatibility"
> https://atom.io/packages/emmet-snippets-compatibility
> 
> Before install the package, remember to delete the code you paste on Keymap.
> it worked for me.

Thanks, @Steve-Hsu! This worked!

**Comment by alanross999** [comment]
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'

Are you entering this into a file you are working on?

**Comment by BitQuarkApps** [comment]
> If you find after installing emmet, tab completion doesn’t work as described in the documentation, go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

Why is this disabled by default tho?

**Comment by Chaitanyab2001** [comment]
> If you find after installing emmet, tab completion doesn’t work as described in the documentation, go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

This didn't help........but uninstalling emmet definitely did

**Comment by lyka-n** [comment]
um neither @tiffanytse nor @Steve-Hsu 's method worked :((

**Comment by Apro123** [comment]
I ran into this same issue. But I simply disabled it and enabled it again and it started to work for me. I don't know if this was specific to my case, but I am just putting this here just in case it might help others.

**Comment by chalokim** [comment]
> If you find after installing emmet, tab completion doesn’t work as described in the documentation, go to **Atom > Keymap** or **File > Keymap** add the following code, then restart Atom (this fix worked for me):
> 
> ```
> 'atom-text-editor:not([mini])':
>   'tab': 'emmet:expand-abbreviation-with-tab'
> ```

Thanks this worked perfectly~
