### ISSUE TITLE
TAB moving to next  edit point can't move to line end

### ISSUE THREAD

**Issue by MarvinXu** [emmetio/emmet-atom#504]
![gif](https://cloud.githubusercontent.com/assets/7382357/24597776/5b6abfae-187a-11e7-8822-faa1bd49e717.gif)

In sublime it works all fine, what should I do here ?

**Comment by sergeche** [comment]
There’s no such option yet on Atom

**Comment by MarvinXu** [comment]
I was wondering what others would do to move to the end of line at this case. use Arrows ? Or End ?

**Comment by sergeche** [comment]
There are many ways to move to the end of line in editor

**Comment by MarvinXu** [comment]
But not as fast as TAB... I'm addicted to this
