### ISSUE TITLE
input, label, span tags not appearing on separate lines or indented

### ISSUE THREAD

**Issue by digita1-Anal0g** [emmetio/emmet-atom#510]
It seems that when an `input`, `label`, or `span` element is included, the resulting html isn't indented.

I'm on:

- atom:  1.17.1
- emmet:  2.4.3
- Other non-core packages installed:  None

No custom keymapping or configuration settings for Atom and no modifications to the default settings of emmet.

Input:  `div>label+input`

Expected:

    <div>
        <label for=""></label>
        <input type="text">
    </div>

Actual:  

    <div><label for=""></label><input type="text"></div>

I've tried other elements/combinations such as:

-  `div>(ul>li*3)+(ol>li*3)`
-  `section>header>h1{Hello World}+a[href='#']{Click Me}^.container>#first-name`

And the resulting html is indented as expected.  As soon as I introduce a label, input, or span, the newlines/indentation no longer appears as expected.  As per #81, I verified that the format of the document is set to HTML.

**Comment by sergeche** [comment]
Both `input` and `label` are inline elements so they are outputted on the same line, same as you’d probably like to output `p>a` as `<p><a href=""></a></p>`.

There are number of options to redefine this behaviour: https://docs.emmet.io/customization/syntax-profiles/

**Comment by digita1-Anal0g** [comment]
Awesome, thanks!
