### ISSUE TITLE
Tab Expansion for Class Names Won't Work in .hbs files

### ISSUE THREAD

**Issue by grayghostvisuals** [emmetio/emmet-atom#517]
When using Handlebars files that end in `.hbs` the feature to hit tab after typing a class name does not expand the markup as it should. This works fine when the file is `.html`

To be clear…

typing `div.test` + tab works in `.html` files, but fails in `.hbs` files.

**Comment by grayghostvisuals** [comment]
Even though my issue is regarding expansion for class names it's also true for pretty much all tab expansion options…

`a[href="test"]`
`div#test`

etc. etc.

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key

**Comment by grayghostvisuals** [comment]
@sergeche TY so much!
