### ISSUE TITLE
Tab does not expand abbreviations with emmet in atom

### ISSUE THREAD

**Issue by Ashcon313** [emmetio/emmet-atom#544]
Having trouble with the Tab key expanding my abbreviations. The ctrl-e button works for me but not sure how to reroute the tab key to perform the same function.

**Comment by wfpc** [comment]
Same here.  I was trying to follow along with this video (https://www.youtube.com/watch?v=aiXNKHKWlmY "**10 Essential Atom Editor Packages & Setup**" by Traversy Media)  on setting up Atom and it showed adding emmet and said that "tab" would auto expand something like div.test, but it doesn't.

When something like this happens, I just don't trust the entire app.  I mean, if the simple stuff won't work, how can I trust it with larger stuff?

**Comment by sergeche** [comment]
Please read README first, there’s everything you need to know about Tab key
