### ISSUE TITLE
Emmet breaks php snippet expansion

### ISSUE THREAD

**Issue by nicolaiskogheim** [emmetio/emmet-atom#58]
Atom 0.73.0
Emmet 0.6.0

As you se below, enabling Emmet breaks snippet expansion for php

![emmet breaks php expansion](https://f.cloud.github.com/assets/2117636/2428290/9ab707b8-ac3e-11e3-86b8-ec6ff56a6623.gif)

**Comment by pierretusseau** [comment]
@felgeekpe works perfectly, thanks :+1: :)
