### ISSUE TITLE
Installing “emmet@2.4.3” failed

### ISSUE THREAD

**Issue by AdrianAcostaPR** [emmetio/emmet-atom#614]
I am trying to install the emmet package but I am getting the following error: 
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adria\.atom\.apm\_logs\2020-01-21T14_59_59_190Z-debug.log

I have tried uninstalling Atom and installing it again but I am still getting the same issue.  Also, I tried to install it via the console with: 
cd ~/.atom/packages
git clone https://github.com/emmetio/emmet-atom
cd emmet-atom
npm install

but I get the following error:
The system cannot find the path specified.

And:
git clone https://github.com/emmetio/emmet-atom
'git' is not recognized as an internal or external command,
operable program or batch file.

Any suggestions?

**Comment by sergeche** [comment]
It says you have no Git installed. Try to install it first: https://git-scm.com

**Comment by AdrianAcostaPR** [comment]
@sergeche it didn't work.
