### ISSUE TITLE
tab expansion shortcut does not expand

### ISSUE THREAD

**Issue by alreadyinuse** [emmetio/emmet-atom#630]
Hello, my issue is that the tab expansion shortcut does not expand.  Searching for tab, expand, and expansion revealed no issues with these words in the title.

I just installed ATOM on Windows 10.  The only installed packages are emmet 2.4.3 and browser-plus 0.0.98

ATOM is  1.47.0 electron 5.0.13 chrome 73.0.3683.121 node v12.0.0

How should meow proceed with troubleshooting this?

Thanks!

**Comment by danditk** [comment]
I have the same problem :(. I tried to reinstal emmet and ATOM, but it's not helped.
Best regards,
Darek

**Comment by sergeche** [comment]
Have you tried this one? https://github.com/emmetio/emmet-atom#tab-key

**Comment by alreadyinuse** [comment]
Hi Sergeche, thanks for your reply.
Yes I did see the readme file but I was not able to understand it.  But I understand it better now that I have some more experience with ATOM. (I am a new user.)
Can I please suggestion some clarification for the readme? 

Features:
Expand abbreviations by Tab key

...will be more clear if be changed to:

Features:
Expand abbreviations by Tab key or by ctrl-e

...

Tab key
Currently, Emmet expands abbreviations by Tab key only for HTML, CSS, Sass/SCSS and LESS syntaxes. 

... will be more clear if changed to:

Tab key
Currently, Emmet expands abbreviations by ctrl-e for all syntaxes, but expands by Tab key only for HTML, CSS, Sass/SCSS and LESS syntaxes.  Please note your document is not considered to be in one of these syntaxes until saved with the appropriate file extension.

Thanks!
-AIU
