### ISSUE TITLE
Miner? 

### ISSUE THREAD

**Issue by Misacardi** [emmetio/emmet-atom#667]
After installation i saw that my PC started working slowly, when i click to win-button win-menu open after 2 sec, I thought it was a miner and checked the pc with an antivirus and it showed me the following result. WTF?
![image](https://user-images.githubusercontent.com/50731973/184914119-341a3dee-f909-4e19-a76e-4919b3c4a85b.png)

**Comment by sergeche** [comment]
The Atom itself is deprecated so it’s better use another editor like VSCode
