### ISSUE TITLE
Change from double quotes to single quotes emmet [$50]

### ISSUE THREAD

**Issue by mannyatico** [emmetio/emmet-atom#68]
Hi there,

I was wondering if there is any way to use the *syntaxProfile.json*, because i want to change from double quotes to single quotes when a shortcut is expanded.

I've already checked the emmet atom package and only says:
> There's no support (yet) for *snippets.json* and *preferences.json*

But there is no mention about *syntaxProfile.json*, so I want to think there is support.

If someone could point me in the right direction, i'll be so grateful.

**Comment by vegetableman** [comment]
@sergeche Please check the issue created. Let me know if any queries.

**Comment by mannyatico** [comment]
Hi everyone, 

I confirm, the workaround pointed by @vegetableman works flawlessly.

I'm gonna close this issue, since the new bug posted by @vegetableman has a better explanation.

Thanks everyone for the support.

**Comment by sheriffderek** [comment]
@vegetableman  -  Could we get a clearly written road map to the solution here, so that others - *who may not have been following along* - can quickly get rid of those pesky double quotes? *What to put where, how to keep it on top of defaults* etc?

**Comment by vegetableman** [comment]
@sheriffderek Sure. To get rid of the issue, create a file called ```profiles.json``` in ```~/emmet``` directory and add the following:
```json
{
 "html": {
    "attr_quotes" : "single"
  }
}
```
And for other profile customisation support, simply add it to the mentioned file instead of ```syntaxProfiles.json```

**Comment by joeldbirch** [comment]
I wonder how we can get this working inside JSX? The `profiles.json` doesn't seem to work. I tried changing `"html" to the below variations hoping for a minor miracle, but no luck.

```js
 "JavaScript": {
    "attr_quotes" : "single"
  },
 "javascript": {
    "attr_quotes" : "single"
  },
 "js": {
    "attr_quotes" : "single"
  },
 "jsx": {
    "attr_quotes" : "single"
  },
 "JavaScript (Babel)": {
    "attr_quotes" : "single"
  }
```

**Comment by JAdshead** [comment]
@joeldbirch This is probably a bit late but to get single quotes working with JSX you will need to update or create the `syntaxProfiles.json` in `~/emmet` with the syntax profile. I believe that the key is the file extension and the value is the name of the profile that extension will use.

So..
```json
/* ~/emmet/syntaxProfiles.json */

/* 'js' will map files with .js extension to use the js profile*/
/* 'jsx' will map files with .jsx extension to also use the js profile*/
{
  "js": "js",
  "jsx": "js"
}
``` 

```json
/* ~/emmet/profiles.json */

/* create or add the 'js' profile */
{
  "html": {
    "attr_quotes": "double"
  },
  "js": {
    "attr_quotes": "single",
    "self_closing_tag": true
  }
}

```

**Comment by lincolnlemos** [comment]
Hey guys, 

How i can make this work in PHP files inside a echo ""?
I try add this in my SyntaxProfiles.

`"php": {
    "attr_quotes" : "single"
  }`

When i type echo "input" and press tab, it gives me:
`echo "<input type="submit" name="" value="">"`

I need:
`echo "<input type='submit' name='' value=''>"`
