### ISSUE TITLE
html abbreviations not working in php file

### ISSUE THREAD

**Issue by Lieneke** [emmetio/emmet-atom#88]
Hi, I would like to be able to use emmet in my php files. 
None of the abbreviations are working, div.class or ul>li*5.item div#container

I have to change my syntax to html to be able to use these abbreviations.

**Comment by silvenon** [comment]
With 2.3.0 you can easily enable the Tab key for any language. Read [this](https://github.com/emmetio/emmet-atom#tab-key) for more info.

**Comment by bounasserabdelouahab** [comment]
+1 having the same issue here.

**Comment by admench** [comment]
For a plain php file, add this to the keymap (Atom -> Keymap...) 

'atom-text-editor[data-grammar="text html php"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'

**Comment by ex-jedi** [comment]
There's a package available, which seems to work well so far.

[Emmet Snippets Compatibility](https://github.com/peterjohnhunt/emmet-snippets-compatibility#emmet-snippets-compatibility)
