### ISSUE TITLE
Unpredictable Behavior

### ISSUE THREAD

**Issue by RyanLutz** [emmetio/emmet-atom#89]
When first installed emmet in atom it worked great and predictably
 if i expanded .content it would create <div class="content"></div>
now it creates <content></content> what is that?
also, it seemed to work great with css and sass. Now it mostly won't expand anything.

I'm going to start completely over with atom. Maybe I just installed to many various packages

**Comment by silvenon** [comment]
Seems like a non-issue then. You can track the snippet expanding issue in #146.
